<div class="work_section_two  mainprofile">
	<form method="post" action="<?=$this->url(array('controller'=>'myaccount', 'action'=>'updatechangepassword'), 'default', true)?>">

		<div class="top10pxmargin " style="margin-top:0px;">
			<label class="myaccsubtitles">Current Password</label>
		</div>

		<div class="top5pxmargin ">
			<?=$this->myform->currentpass?>
		</div>

		<div class="top10pxmargin ">
			<label class="myaccsubtitles">New Password</label>
		</div>

		<div class="top5pxmargin ">
		<?=$this->myform->newpass?>
		</div>

		<div class="top10pxmargin ">
			<label class="myaccsubtitles">Confirm New Password</label>
		</div>

		<div class="top5pxmargin ">
			<?=$this->myform->cnfrmnewpass?>
		</div>



		<div class="top10pxmargin ">
			<input type="submit" name="submit" id="submit" value="Save Changes" class="accbutton">
			<a href="<?=APPLICATION_URL?>myaccount/profile" style="text-decoration:none;"> <input type="button" name="cancel" id="cancel" value="Cancel" class="accbutton"> </a>
		</div>

	</form>
</div>

