<?php
global $mySession;
$db=new Db();
$userid=$mySession->TeeLoggedID;

	$campstatus=$this->Data[0]['campaign_status'];

	//$finishes=$this->day_difference;

?>

<div style="width:100%; float:left;">

        <div style="margin-top:10px; width:790px;">

            <label class="myaccheading">Ended Campaigns<br /></label>

             <hr style="width:780px; color:#999;" align="left"/>

            <?php
			if($this->nocamp!="")
			{
			?>

                <label style="font-family:'Arial Black', Gadget, sans-serif; color:#000; font-size:14px;">You Don't Have any Ended campaigns.
                </label>
            <?php
			}

			if(count($this->Data)>0 && $this->Data!="")
			{
				$i=0;
				foreach($this->Data as $key=>$value)
				{

             // prd($value);
              $row1=$db->runQuery("select DATE_ADD('".$value['launch_date']."', INTERVAL '".$value['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$value['launch_date']."', INTERVAL -1 DAY) AS prevDate");

		$enddate=$row1[0]['nextDate'];

		$newdat2=explode(" ",$enddate);
		$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format
		$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format
		//$this->view->newdat4=$newdat4;
		//echo "ended on ".$newdat4;
	?>


                <div style="width:780px; height:80px;">

                    <div style="width:320px; height:80px; float:left">

                        <div style="width:70px; height:70px; float:left;">
                        	<img src="<?=IMAGES_URL?>designtee.png" width="70" height="70" />
                        </div>

                            	<div style="height:80px; width:5px; float:left">
                                </div>

                        <div style="float:left;">

                            <div style="width:230px; height:28px; font-size:18px; font-family:Tahoma; color:#003399;">
                            	<b> <?php echo $value['title']; ?></b>
                            </div>

                            <div style="width:230px; height:20px;">
                            	<div align="center" style="height:8px; width:200px; background-color:#060; border-radius:8px;">
                                 </div>
                            </div>

                             <?php $campid = $value['campaign_id'];

							?>


                           <div style="width:230px; height:20px;">
                           		<a href="<?=APPLICATION_URL?>launchcampaign/setgoal/cid/<?=$campid?>">
                                <div style="float:left; font-family:Corbel; font-size:14px; color:#666;">
                                	 relaunch campaign
                                </div>  </a>

                                <a href="<?=APPLICATION_URL?>">
                                <div style="float:left; font-family:Corbel; font-size:14px; color:#666;">
                               		&nbsp;| send thank you
                               </div></a>


                            </div>

                        </div>


                    </div>

                    		<div style="width:50px; height:80px; float:left">

                            </div>

                    <div style="width:200px; height:80px; float:left; ">

                            <div style="width:200px; height:30px;">
                            </div>
                            <div style="font-family:Corbel; font-size:18px; color:#666666; margin-left:20px;">
								<?php  echo $value['sold']; ?>&nbsp; of &nbsp;<?php echo $value['goal']; ?>&nbsp; sold
                            </div>
                    </div>

                    		<div style="width:50px; height:80px; float:left">
                            </div>

                     <div style="width:150px; height:80px; float:left;">

                            <div style="width:200px; height:30px;">
                            </div>
                            <div style="font-family:Corbel; font-size:18px; color:#666666; margin-left:20px;">
                            	ended on &nbsp; <?php echo $newdat4 ?>
                            </div>
                     </div>



                </div>

                <div>
                	 <hr style="width:780px; color:#999;" align="left"/>
                </div>

            <?php
				}
				$i++;
			}
			?>

        </div>

</div>

