<?php
global $mySession;
$db=new Db();
$userid=$mySession->TeeLoggedID;
$Data=$db->runQuery("select * from ".LAUNCHCAMPAIGN." WHERE user_id='".$userid."' and campaign_status='1'");
foreach($Data as $key=>$value)
{
	$row1=$db->runQuery("select DATE_ADD('".$value['launch_date']."', INTERVAL '".$value['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$value['launch_date']."', INTERVAL -1 DAY) AS prevDate");
	$enddate=$row1[0]['nextDate'];
	$newdat2=explode(" ",$enddate);
	$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format
	$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format
	$diff = strtotime($enddate) - strtotime(date('Y-m-d H:i:s'));
	$day_difference = floor($diff / (60*60*24));
	if($day_difference<=0)
	{
		$dataUpdate['campaign_status']=0;
		$conditionUpdate="campaign_id='".$value['campaign_id']."'";
		$db->modify(LAUNCHCAMPAIGN,$dataUpdate,$conditionUpdate);
	}
}



$Data1=$db->runQuery("select * from ".LAUNCHCAMPAIGN." WHERE user_id='".$userid."' and draft_status='0'");
if($Data1!="" and count($Data1)>0)
{
	$qury=$db->runQuery("select * from ".DRAFTS." WHERE user_id='".$userid."' and campaign_id='".$Data1[0]['campaign_id']."'");
	if($qury!="" and count($qury)>0)
	{

	}
	else
	{
		foreach($Data1 as $key=>$value)
		{

			echo "camp id of draft :".$value['campaign_id'];
			$data_insert['campaign_id']=$value['campaign_id'];
			$data_insert['user_id']=$userid;
			$db->save(DRAFTS,$data_insert);
		}
	}
}

?>
<style type="text/css">
    .errormsg{
        color:red;
    }
</style>
<div class="work_section_two  mainprofile">
	<div class="rowprofile" >
        <div class="col1" style="padding-bottom: 100px">
			<form method="post" action="<?=$this->url(array('controller'=>'myaccount', 'action'=>'updateuser'), 'default', true)?>" enctype="multipart/form-data" onsubmit="return validateInputs();">
				<div class="top5pxmargin">
					<label class="myaccsubtitles">Public Name</label>
				</div>
				<div class="top5pxmargin">
				<?=$this->myform->publicname?>
                    <span id="publicname-msg" class="errormsg"></span>
				</div>
				<div class="top5pxmargin">
					<label class="smallsubtext">
					This name will appear on your campaign
					</label>
				</div>
				<div class="top10pxmargin ">
					<label class="myaccsubtitles">Email</label>
				</div>
				<div class="top5pxmargin">
					<?=$this->myform->emailid?>
                    <span id="emailid-msg" class="errormsg"></span>
				</div>
				<div class="top10pxmargin ">
					<label class="myaccsubtitles">BIO</label>
				</div>
				<div class="top5pxmargin">
					<?=$this->myform->bio?>
					<br /><label class="smallsubtext">Max 300 Characters</label>
                    <span id="bio-msg" class="errormsg"></span>
				</div>
				<div class="top10pxmargin ">
					<label class="myaccsubtitles">Profile Image</label>
				</div>
				<div class="top5pxmargin">
					<?=$this->myform->profile_image?>
					<?=$this->myform->old_profile_image?>
				</div>
				<div class="top10pxmargin ">
					<label class="myaccsubtitles">Password</label>
				</div>
				<div class="top5pxmargin">
					<span class="myacclink"> <a href="<?=APPLICATION_URL?>myaccount/changepassword">Click here to change your password </a> </span>
				</div>
				<div class="top10pxmargin">
					<input type="submit" name="submit" id="submit" value="Save Changes" class="accbutton">
					<a href="<?=APPLICATION_URL?>myaccount/profile" style="text-decoration:none;"> <input type="button" name="cancel" id="cancel" value="Cancel" class="accbutton"> </a>
				</div>
			</form>
		</div>
		<div class="col2">
<!--			<div  class="pimg" onmouseover =this.style.backgroundColor='#f7f7f7' onmouseout=this.style.backgroundColor='#ffffff'>-->
			<?php if($this->userdatapic['profile_image']!="" && file_exists(SITE_ROOT.'images/profileimages/'.$this->userdatapic['profile_image'])) { ?>
				<img src="<?=APPLICATION_URL?>images/profileimages/<?=$this->userdatapic['profile_image']?>" height="120" width="120" border="0" style="border: solid 1px #cccccc;padding:2px;" />
			<?php }  else  { ?>
				<img src="<?=APPLICATION_URL?>images/profileimages/bothDefault_image.jpg" height="120" width="120" border="0"   />
			<?php } ?>
		</div>
	</div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){

    });
    function validateInputs(){
        var publicname = $('#publicname').val();
        var emailid = $('#emailid').val();
        var bio = $('#bio').val();
        var error = 0;

        if(publicname.length <= 0){
            $('#publicname-msg').html('Please enter a public name');
            error++;
        }else{
            $('#publicname-msg').html('');
        }
        if(emailid.length <= 0){
            $('#emailid-msg').html('Please enter your email address');
            error++;
        }else{
            $('#emailid-msg').html('');
        }
        if(bio.length <= 0){
            $('#bio-msg').html('Please enter a short bio');
            error++;
        }else{
            $('#bio-msg').html('');
        }
        if(error > 0){
            return false;
        }
        return true;
    }
</script>