<?php
global $mySession;
$db=new Db();
?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<!-- bxSlider Javascript file -->

<!--<script src="<?=APPLICATION_URL?>jquery.bxslider/jquery.bxslider.js"></script>-->

<script src="<?=APPLICATION_URL?>jquery.bxslider/jquery.bxslider.min.js"></script>
<!-- bxSlider CSS file -->
<link href="<?=APPLICATION_URL?>jquery.bxslider/jquery.bxslider.css" rel="stylesheet" />



<!--<script type="text/javascript">

$(document).ready(function(){
	//alert("fdhdfh");
  $('.bxslider').bxSlider();
  
});

</script>
-->

<script type="text/javascript">
$(document).ready(function(){
  $('.bxslider').bxSlider();
});
</script>




<div style="width:100%; height:auto;" align="center">
           
     <!--<div style="max-width:100%; height:475px; background-image:url(<?=IMAGES_URL?>backgreen.png); background-repeat:no-repeat; background-position:center">-->
    
     <div style="width:100%; background-position:center">
           
       
                <div style="width:1000px; height:475px; display:inline-block; ">
               <!------content1--------->
                    
                  
                   
                    <div align="left" style="width:1000px; height:300px;">    
                         
                         
                         <div style="float:left; width:533px; height:300px; float:left;" class="fontheading">
                    
                        	<div style="height:50px;">
                             &nbsp;
                            </div>
                            
                            <div style="width:10px; height:250px; float:left">
                            </div>
                            
                            <div style="width:520px; float:left">
                               <label>Create & Sell Custom T-Shirts with <br/>
                                 Zero Upfront Costs.<br/> </label>
                             </div>
                                
                               <div style="height:3px; width:513px; float:left;">
                               </div>
                               
                               <div class="subtitles" style="width:517px; height:50px; float:left;">
                                    
                                   
                                    
                                    <div style="width:14px; height:15px; margin-left:13px; float:left;">
                                      <img src="<?=IMAGES_URL?>textarrow.png"  />
                                    </div>
                                   
                                    <div style="margin-left:9px; width:475px; float:left; height:20px; white-space:nowrap;"> No Upfront Costs, no risks. Buyers pre-order their tees online on your   
                                    </div>
                                     
                                     <div style="width:513px; height:8px; float:left">
                                     </div>
                                     
                                     <div style="margin-left:35px; width:480px; height:20px;"> campaign page, so you don't get stuck paying the bills.</div>
                                 
                                 </div>
                                 
                                 <div style="width:515px; height:35px; float:left">
                                 </div>
                                 
                                 <div class="subtitles" style=" height:45px; width:513px; float:left">
                                  
                                    <div style="width:14px; height:15px; margin-left:13px; float:left;">
                                      <img src="<?=IMAGES_URL?>textarrow.png" />
                                    </div> 
                                      
                                      
                                      <div style="margin-left:9px; width:475px; float:left; height:20px; white-space:nowrap;"> 
                                        High-quality prints. We only use retail-quality screen printing (no digital <br/>
                                       </div>
                                     
                                     <div style="width:513px; height:8px; float:left">
                                     </div>
                                     
                                        <div style="margin-left:35px; width:480px; height:20px;">
                                            prints) so you get a t-shirt you can be proud of.
                                        </div>
                                 </div>
                             
                          
                        </div>
                        
                        <div style="margin-right:0px; width:460px; height:300px; float:left;">
                            
                                  <img src="<?=IMAGES_URL?>2t-shirt.png"/>
                            
                       </div>
                   
                   </div>
               <!------content1--------->
               
            
              
               <!-------content2---------->	
          
                    <div align="left" style="width:1000px;">
                    
                        <div style="float:left; width:650px" >
                        	<div style="height:85px;">
                            &nbsp;
                            </div>
                            
                            <div>
                                <label style="font-family:aaarghnormal; margin-left:10px; font-size:30px; color:#177e40;">
                                    Custom T-Shirt Printing <br/>
                                </label>
                        
                        
                                <label style="font-family:'Bradley Hand ITC'; font-size:24px; color:#959595;">
                                    &nbsp;&nbsp;Personalise Clothing with text, designs or photos
                                </label>
                             </div>
                              
                       </div>
                      
                   
                        <div style="float:left; margin-top:40px;">
                             <!--  <a style="cursor:pointer;" href="<?=APPLICATION_URL?>login/index/l/launch"> <img src="<?=IMAGES_URL?>getstartedbtn.png" /> </a>-->
                               <a style="cursor:pointer;" href="<?=APPLICATION_URL?>launchcampaign/index"> <img src="<?=IMAGES_URL?>getstartedbtn.png" /> </a>
                        </div>
                       
                  </div>            
               <!-------content2---------->
              </div>
           
     </div>
     
     <div style="max-width:100%; background-image:url(<?=IMAGES_URL?>backgrnd2.png); background-repeat:repeat-x;"> 
           
            <!-------content3---------->	
               <div align="center" style="width:1000px; height:261px;">
            	
                    <div style="float:left; width:245px; height:198px; margin-left:98px; margin-top:28px;">
                            
                            <div style="margin-left:-20px; margin-bottom:2px">
                                <label style="font-family:Arial; font-size:23px; color:#0dcd5a">
                                    <b> 1. Select your Product</b>
                                </label>
                            </div>
                            
                            <div>
                                <img src="<?=IMAGES_URL?>tshirt1st.png" />
                            </div>	
                          
                   </div>
                   
                   <div style="float:left; width:75px; margin-top:24px; margin-left:-10px">
                        <img src="<?=IMAGES_URL?>broadarrow.png" />
                   </div>
                   
                   <div style="float:left; width:247px; margin-top:29px; height:198px;">
                    
                        <div style="width:245px;">
                            <label style="font-family:Arial; font-size:23px; color:#0dcd5a">
                                <b> 2. Create your Design</b>
                             </label>
                        </div>
                        
                        <div>
                            <img src="<?=IMAGES_URL?>image2.png" height="202" width="244"/>
                        </div>
                        
                   </div>
                   
                   <div style="float:left; width:75px; margin-top:23px; margin-left:-10px">
                        <img src="<?=IMAGES_URL?>broadarrow.png" />
                   </div>
                   
                   <div style="float:left; width:245px; height:198px; margin-top:28px;">
                    
                        <div>
                           <label style="font-family:Arial; font-size:23px; color:#0dcd5a">
                                <b> 3. We do our Magic</b>
                             </label>
                        </div>
                        
                        <div>
                            <img src="<?=IMAGES_URL?>image3.png" />
                        </div>
                   </div>
                    
              
            </div> 
            <!-------content3---------->
      </div>  
      
          
            
      <div style="max-width:100%; background-image:url(<?=IMAGES_URL?>backgrnd3.png); background-repeat:repeat-x;">
            <!-------content4---------->	
              
               <div align="center" style="width:1000px; height:383px;">
            	
                	 <div style="margin-bottom:2px;" align="left">
                        	<label style="font-family:aaarghnormal; font-size:30px; color:#177e40;">
                            	Check out our featured campaigns
                            </label>
                     </div>
                   
                    <div>
                    

                        <div class="bxslider" style="padding:0px; margin:0px;width:500px;">
                        
     <?php     
	 $slid=$db->runquery("select * from ".LAUNCHCAMPAIGN." where slider_status='1'");
	  
	   if(count($slid)>0 && $slid!="")
			{
				
				foreach($slid as $key=>$value)
				{
					
				 $row1=$db->runQuery("select DATE_ADD('".$value['launch_date']."', INTERVAL '".$value['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$value['launch_date']."', INTERVAL -1 DAY) AS prevDate");
		
		$enddate=$row1[0]['nextDate'];
              
		$newdat2=explode(" ",$enddate);
		$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format
		$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format
		//$this->view->newdat4=$newdat4;
		
		$diff = strtotime($enddate) - strtotime(date('Y-m-d H:i:s'));	
	
		$day_difference = floor($diff / (60*60*24));
			
		if($day_difference>0)
		
			{
				
				 $years = floor($diff / (365*60*60*24));
 				 $months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
				 $days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
 				 $hours = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24- $days* 60*60*24)/(60*60));
				
			}
			if($day_difference<=0)
			{
				//$this->view->day_difference=$day_difference;
				$dataUpdate['campaign_status']=0;
				$conditionUpdate="campaign_id='".$value['campaign_id']."'";
				$db->modify(LAUNCHCAMPAIGN,$dataUpdate,$conditionUpdate);
				
			}
		
              
					
					
					
					$s=$value['sold']; $g=$value['goal']; @$w=($s/$g)*100; 
					?>
                            <div style="width:100%; height:340px;">
                            	
                                <div style="width:305px; float:left; height:318px; margin-left:65px; margin-top:15px;">
                                	
                                    <img src="<?=IMAGES_URL?><?=$value['tee_image']?>" width="270" height="318"/>
									
                                	<!--<img src="<?=IMAGES_URL?>slidertee.png" />-->
                                    
                                </div>
                                
                               <!-- <div style="width:150px; height:60px; float:left; font-family:'Comic Sans MS'; font-size:30px; color:#333; margin-top:258px; margin-left:-280px;">-->
                                	<!--<img src="<?=IMAGES_URL?>sliderimgname.png" />-->
                                   <!-- <?php echo $value['title']?>
                                </div>-->
                            	
                                <div align="left" style="width:485px; height:230px; float:left; margin-left:10px; margin-top:15px;">
                                  	
                                   <!-- <div style="width:470px; height:45px;">
                                    	<img src="<?=IMAGES_URL?>teeheading.png" />
                                    </div>-->
                                    
                                    <div style="width:470px; height:45px; text-align:center; font-family:'Comic Sans MS'; font-size:30px; color:#030;">
                                    	  <?php echo $value['title']?>
                                    </div>
                                    
                                    <div style="float:left; width:480px; height:160px; margin-top:10px; margin-left:8px;">
                                    	<!--<div style="font-family:'Arial Black'; font-size:14px; color:#606060; width:470px; height:150px; border:#009 solid 1px;">-->
                                        	
                                             <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:10px;">
                                               <tr>
                                               <td align="left" valign="top">
                                              
                                                
												<?php
												
												//   
//												 $descripsub=substr($value['description'],0,100)."...";
//												 
//                                                $data=str_replace("width:"," ",$value['description']);
//                                                $data=str_replace("height:"," ",$data);
//                                                $data=str_replace("float:"," ",$data);
//                                                //echo $data=str_replace("nowrap"," ",$data);
//												$data=str_replace("nowrap"," ",$data);		
//												echo substr($data,0,170)."..." ;
															   
                                        
                                               
                                                $datasub=strip_tags($value['description']);
												echo $datasub=substr($datasub,0,170)."...";
												
												
												//strip_tags(substr($value['description'],0,100)."...");
												// $descripsub=substr($value['description'],0,100)."...";
												 
                                                //$data=str_replace("width:"," ",$value['description']);
                                                //$data=str_replace("height:"," ",$data);
//                                                $data=str_replace("float:"," ",$data);
                                              // echo $data=str_replace("nowrap"," ",$data);
											    //$data=str_replace("nowrap"," ",$data);		
												//echo $final = substr($data,0,170)."..." ;
															   
                                               ?>
                                               </td>
                                               </tr>
                                               </table>
                                         
                                                   
                                                   <?php /*?> <?=substr($value['description'],0,170)."..." ?><?php */?>
                                                  
                                           
                                       <!-- </div>-->
                                    </div>
                                    	
                                 </div>
                                 
                                 <div align="left" style="width:275px; height:80px; float:left; background-image:url(<?=IMAGES_URL?>teebarborder.png); background-repeat:no-repeat; margin-left:20px;">
                                 	<div style="width:200px; height:20px; margin-top:8px; margin-left:10px;">
                                    	<label style="font-family:'Arial'; font-size:17px; color:#606060">
                                        	<b>$ <?php echo $value['selling_price'] ?></b>
                                        </label>
                                        <label style="font-family:'Arial'; font-size:12px; color:#606060; font-weight:normal;">
                                        	<?php echo $value['sold'] ?> of <?php echo $value['goal'] ?> reserved
                                        </label>
                                    </div>
                                    
                                    
                          
                                    <div style="width:255px; margin-top:4px; margin-left:10px;">
                                    	<!--<img src="<?=IMAGES_URL?>greenbar.png" />-->
                                                     <?php if($w<100)
						   {
							  
						   ?>
                              <div style="width:100%;height:8px;border:1px solid #393 ;border-radius:8px; ">
                           <div align="center" style="height:8px; width:<?=@$w?>%; border-radius:8px;border:0px solid #393 ; background-color:#339933">
                                </div>
                                </div>
                                <?php
						   }
						   else
						   {
							  
								?>
                                   <div style="width:100%;height:8px;border:1px solid #393 ;border-radius:8px; ">
                            	<div align="center" style="height:8px; width:100%; border-radius:8px;border:0px solid #393 ; background-color:#339933">
                                </div>
                                  </div>
                                <?php
						   }
						   ?>
                                        <!-- <div style="width:100%;height:8px;border:1px solid #393 ;border-radius:8px; ">
                                            <div align="center" style="height:8px; width:<?=@$w?>%; border-radius:8px;border:0px solid #393 ; background-color:#339933">
                                            </div>
                                    	</div>-->
                                    </div>
                                    
                                    <div style="margin-top:5px; margin-left:13px;">
                                    	<div style="width:13px; height:14px; float:left;">
                                    	   <img src="<?=IMAGES_URL?>timerclock.png" />
                                        </div>
                                        
                                         <?php
								    if($day_difference>0)
									 {
								   ?>   
                                      
                                       <div style="font-family:'Arial'; font-size:12px; color:#606060; font-weight:normal;">
                                        	 <?=$days?> days and <?=$hours?> hours left.
                                        </div>
                                        <?php
									 }
									 else
									 {
									 ?>
                                     	<div style="font-family:'Arial'; font-size:12px; color:#606060; font-weight:normal;">
                                        	This campaign ended on <?=$newdat4?>
                                        </div>
                                     <?php
									 }
									 ?>
                                    	<!--<label style="font-family:'Arial'; font-size:10px; color:#606060; font-weight:normal;">
                                        	&nbsp;2 days and 20 hours left
                                        </label>-->
                                    </div>
                                  
                                    
                                 </div>
                                 
                                 <div style="float:left; width:245px; height:50px; margin-top:42px; margin-left:20px">
                                 	<!--  <a href="<?=APPLICATION_URL?>launchcampaign/showcampaign/show/s/name/<?=$value['url']?>"><img src="<?=IMAGES_URL?>viewcampaignbtn.png" /></a>-->
                                     <a href="<?=APPLICATION_URL?><?=$value['url']?>"> 
                                     <img src="<?=IMAGES_URL?>viewcampaignbtn.png" />
                                     </a>
                                 </div>
                            </div>
                            
                      <!--    <div style="width:200px; height:350px;">
                            	
                                <div style="width:305px; float:left; height:240px; margin-left:65px; margin-top:15px;">
                                	
                                	<img src="<?=IMAGES_URL?>tshirt1st.png" width="270" height="220" />
                                    
                                </div>
                                
                                <div style="width:150px; height:60px; float:left; margin-top:258px; margin-left:-280px;">
                                	<img src="<?=IMAGES_URL?>sliderimgname.png" />
                                </div>
                            	
                                <div align="left" style="width:485px; height:230px; float:left; margin-left:10px; margin-top:15px;">
                                  	
                                    <div style="width:470px; height:45px;">
                                    	<img src="<?=IMAGES_URL?>teeheading.png" />
                                    </div>
                                    
                                    <div style="float:left; width:480px; height:160px; margin-top:10px; margin-left:8px;">
                                    	<div style="font-family:'Arial Black'; font-size:14px; color:#606060; width:470px; height:150px;">
                                        	<?php echo $slid['description']?>
                                           
                                        </div>
                                    </div>
                                    	
                                 </div>
                                 
                                 <div align="left" style="width:275px; height:80px; float:left; background-image:url(<?=IMAGES_URL?>teebarborder.png); background-repeat:no-repeat; margin-left:20px;">
                                 	<div style="width:200px; height:20px; margin-top:8px; margin-left:10px;">
                                    	<label style="font-family:'Arial'; font-size:17px; color:#606060">
                                        	<b>$20.00</b>
                                        </label>
                                        <label style="font-family:'Arial'; font-size:14px; color:#606060; font-weight:normal;">
                                        	63 of 50 reserved
                                        </label>
                                    </div>
                                    
                                    <div style="width:255px; margin-top:4px; margin-left:10px;">
                                    	<img src="<?=IMAGES_URL?>greenbar.png" />
                                    </div>
                                    
                                    <div style="margin-top:5px; margin-left:13px;">
                                    	<div style="width:13px; height:14px; float:left;">
                                    	   <img src="<?=IMAGES_URL?>timerclock.png" />
                                        </div>
                                    	<label style="font-family:'Arial'; font-size:10px; color:#606060; font-weight:normal;">
                                        	&nbsp;2 days and 20 hours left
                                        </label>
                                    </div>
                                
                                    
                                 </div>
                                 
                                 <div style="float:left; width:245px; height:50px; margin-top:42px; margin-left:20px">
                                 	 <a href="<?=APPLICATION_URL?>launchcampaign/showcampaign/name/.<?=$slid['url']?>"><img src="<?=IMAGES_URL?>viewcampaignbtn.png" /></a>
                                 </div>
                            </div>-->
                            
                          <?php
				}
			}
			?>
                            <!-- <img src="images/sliderimage.png" width="300" height="320" />
                            
                             <img src="images/2t-shirt.png"  width="300" height="320" />-->
                            
                        </div>
                    	
                    </div>
                    
            </div>	
            <!-------content4---------->	
      </div>
      
      
       <div style="max-width:100%; background-image:url(<?=IMAGES_URL?>backgrnd4.png); background-repeat:repeat-x;">
      	    <!-------content5---------->
            <div style="width:1000px; height:12px;">
            </div>
            	
             <!--   <div align="center" style="width:1000px; height:297px;">-->
                <div align="center" style="width:1000px; height:278px;">
            		
                <div style="margin-bottom:2px; width:540px; height:278px; float:left;" align="left"> 
                   <div style="height:25px;">
                        	<label style="font-family:aaarghnormal;  font-size:20px; color:#177e40;">
                            	Find Inspiration
                            </label>
                            <label style="font-family:aaarghnormal; font-size:14px; color:#606060;">
                            	Exciting campaign on teespring
                            </label>
                             
                     </div>
                    
                 <!--  <div style="width:540px; height:250px; background-color:#FFF;position:absolute">
                   		<div style="margin-top:8px; margin-left:8px;">
                           <img src="<?=IMAGES_URL?>loopimg.png" />
                        </div>
                   </div>-->
                       <div style="width:540px; height:250px; background-color:#FFF;position:absolute">
                           <div style="width:540px; height:auto;margin-top:10px;margin-left:10px;"> 
                            <?php
		$slid=$db->runquery("select * from ".LAUNCHCAMPAIGN." where campaign_status='1' and admin_status='1'");
	  
	   if(count($slid)>0 && $slid!="")
			{
                            $k=0;
                            for($i=0; $i<count($slid); $i++)
						  /*  for($i=0; $i<32; $i++)*/
                            {
                                
                            ?>
                                   <div style="width:64px; height:58px; float:left; padding:0px; margin:0px; border:#ffffff solid 1px;">
                                   		<!--<a href="<?=APPLICATION_URL?>launchcampaign/showcampaign/name/<?=$slid[$i]['url']?>"><img src="<?=IMAGES_URL?>featuredimg.png" /></a>-->
										
                                          <a href="<?=APPLICATION_URL?><?=$slid[$i]['url']?>"> <img src="<?=IMAGES_URL?>featuredimg.png" /> </a>
                                        
                                   </div>
                                    <!--<img src="images/featuredimg.png" width="64" height="58" style="padding:0px; margin:0px; margin-top:-3px; margin-left:-2px; border:#FFFFFF thin 1px;" />-->
                               <?php
                                $k++;
                                if($k%8==0)
                                {
                                    ?>
                                    <br/>
                                    <?php
                                }
                                
                            }
			}
                            ?>
                           </div>       
                          </div>
                     
                            
                  </div>
                   
                   
                <!--  <div style="float:left; margin-left:10px; height:290px; width:410px; border:#033 solid 1px;"> -->
                  <div style="float:left; margin-left:10px; height:270px; width:410px;"> 
                       <div align="left" style="height:25px;"> 
                     	
                        	<label style="font-family:aaarghnormal; margin-left:10px; font-size:20px; color:#177e40;">
                            	Testimonials
                            </label>
                            <label style="font-family:aaarghnormal; font-size:14px; color:#606060;">
                            	What people are saying
                            </label>
                            
                       </div>
     
     <?php
	 $qur=$db->runquery("SELECT * FROM  ".TESTIMONIALS." where testimonials_id='2'");
	 ?>
                       
                       <div style="width:425px; float:left; height:240px; margin-top:3px; margin-left:3px; background-image:url(<?=IMAGES_URL?>testimBG.png); background-repeat:no-repeat;">
                       		<div align="left" style="margin-top:12px; float:left; margin-left:10px;">
                               <img src="<?=IMAGES_URL?>testimoaudio.png" />
                            </div>
                            
                            <div  style="margin-top:15px; float:left; margin-left:20px;">
                            	<label style="font-family:'Palatino Linotype'; font-size:18px; color:#177e40;">
                                	-<?=$qur[0]['testimonials_name'];?>
                                </label>
                                <label style="font-family:'Palatino Linotype'; margin-left:10px; font-size:18px; color:#606060;">
                                	-<?=$qur[0]['testimonials_sitename'];?>
                                </label>
                            </div>
                            
                            <div style="float:left; margin-top:20px; margin-left:20px;">
                            	<div style="float:left; height:62px; width:62px;">
                                	 <img src="<?=IMAGES_URL?><?=$qur[0]['testimonials_image']?>" height="62" width="62" />
									
                                    <!--<img src="<?=IMAGES_URL?>testimoprofileimg.png" />-->
                                </div>
                                
                                <div style="float:left; text-align:left; margin-left:10px; width:310px; height:150px;">
                                	<div style="font:'Arial'; font-weight:normal; font-size:14px; color:#606060;">
                                    	<?=$qur[0]['testimonials_data'];?>
                                    </div>
                                </div>
                            </div>
                           <!-- <img src="images/testimonial.png" />-->
                            
                       </div>
                     
                   </div>               
           
            </div>
            <!-------content5---------->	
       </div>
      
</div>

           
     

