<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="../../../../../emadspace/admin/css/psd.css" />
<title>Untitled Document</title>
</head>

<body class="main">


<table align="center" cellpadding="0" cellspacing="0" width="100%" height="55">

<tr>
<td width="100%" class="back"  valign="middle" height="50" id="switcher">
<span class="heading1" >emadspace</span>
</td>
</tr>

<tr>
<td width="100%" class="back1" valign="middle" height="60"  align="center">
<span class="text" >Administrative Control Panel</span>


</td>
</tr>

<tr ><td width="100%" height="2" style="border-bottom:1px solid #CCC;" valign="top"></td></tr>

<tr >
<td width="50%"  valign="top" align="left" >


<table cellpadding="0" cellspacing="0" width="80%" height="auto" align="center" border="0" >
<tr>




<td width="367" align="center" >



        <div class="loginContainer" >
            <form novalidate="novalidate" class="form-horizontal" action="" id="loginForm" >
                <div class="form-row row-fluid">
                    <div class="span12">
                        <div class="row-fluid">
                            <label class="form-label span12" for="username">
                                Username:
                                <br />
                                <span class="icon16 right gray marginR10">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                            </label>
                            <input class="span12 text" id="username" name="username" value="Administrator" type="text">
                        </div>
                    </div>
                </div>

                <div class="form-row row-fluid">
                    <div class="span12">
                        <div class="row-fluid">
                            <label class="form-label span12" for="password">
                                Password:
                                <br />
                                <span class="icon17 right gray marginR10">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                               
                            </label>
                            <input class="span12 password valid" id="password" name="password" value="somepass" type="password">
                        </div>
                    </div>
                </div>
                <div class="form-row row-fluid">                       
                    <div class="span12">
                        <div class="row-fluid">
                            <div class="form-actions">
                            <div class="span12 controls">
                      
                                <button type="submit" class="btn btn-info right" id="loginBtn"><span class="icon16 icomoon-icon-enter white"></span> Login</button>
                                
                            </div>
                            </div>
                           
                        </div>
                    </div> 
                </div>

            </form>
        </div>



</td>




</tr>
</table>


</td>
</tr>






</table>


</body>
</html>