<?php
global $mySession;
$db=new Db();
?>

<link rel="stylesheet" type="text/css" href="<?=CSS_URL?>mainpage.css"/>
<link rel="stylesheet" type="text/css" href="<?=CSS_URL?>inner.css"/>

<script type="text/javascript" src="<?=APPLICATION_URL?>fancybox/lib/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="<?=APPLICATION_URL?>fancybox/source/jquery.fancybox.js?v=2.1.0"></script>
  <script type="text/javascript">
	$(document).ready(function() {
														
								
	$('#edit1').fancybox();
												
	});
	</script>

<link rel="stylesheet" href="<?=APPLICATION_URL?>fancybox/source/jquery.fancybox.css?v=2.1.0" media="screen"  />
<table cellpadding="0" cellspacing="0" border="0"  align="center">
                    
<tr><td>	
<tr><td  width="900" >
              
<table cellpadding="3" cellspacing="3" width="845" border="0" align="center">
<tr>
<td colspan="3" height="20" align="left" valign="top">
    
    <a id="edit1"  href="#inline1" style="font-size:10px; color:#000000">Edit</a>
    
    
    
    


    <div id="inline1" style="width:500px; height:250px; display: none;">
	hello
	</div>
   
</td>
</tr>



</table>

</td></tr>
</table>      

             
                            
                            
