<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title><?=SITE_NAME?> <?php if($this->pageTitle!="" ) { echo " - ".$this->pageTitle; } ?></title>

<link rel="stylesheet" href="<?=CSS_URL?>mycss.css" type="text/css">

<link rel="stylesheet" href="<?=CSS_URL?>jquery.countdown.css" type="text/css">

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<script src="<?=JS_URL?>jquery-1.4.1.min.js"></script>

<!--<script type="text/javascript" src="<?=APPLICATION_URL_ADMIN;?>js/jquery-ui.js"></script>-->

<script src="<?=JS_URL?>jquery 1.9.js"></script>

<script src="<?=JS_URL?>general.js"></script> 

<script src="<?=JS_URL?>jquery.countdown.js"></script>

     <script>

    $("#myInformationDiv").ready(function () { 

      $("#myInformationDiv2").show(1000);

    });

setTimeout(function() {

      $("#myInformationDiv2").hide("fast", function () {

        // use callee so don't have to name the function

        $(this).prev().hide("fast", arguments.callee); 

      });

	  }, 7000);

</script>

<style>

.info_textData

{

	width:229px;

	background-color:#000;

	color:#fff;

	font-size:12px;

	font-family:Arial, Helvetica, sans-serif;

	height:30px; 

	padding:5px;

	margin-left:117px;

	margin-top:30px;

	border-radius:3px 3px 3px 3px;

	display:none;

	opacity:0.9;

	

}

</style>

</head>

<?php

global $mySession;

$db=new Db();

?>

<div align="center" style="width:100%; background-image:url(<?=IMAGES_URL?>mainbackg.png); background-repeat:repeat;">

<div align="center" style="width:100%; height:auto;">

        <div style="width:1000px; height:93px;">

        	<div style="width:1000px; height:10px;">

            </div>

            <div class="dicvrsupprt" align="center" style="width:340px; height:83px; background-image:url(<?=IMAGES_URL?>discvrsupprt.png); background-repeat:no-repeat;">

                <b>

                <?php if($this->category=='discover')

				{ ?>

                <a href="<?=APPLICATION_URL?>" id="selected"> Discover </a><span style="color:#174f5d; margin:0px 8px 0 0px;">|</span><a href="<?=APPLICATION_URL?>index/support">Support</a> 

                <?php } else if($this->category=='support'){?>

                <a href="<?=APPLICATION_URL?>" > Discover </a><span style="color:#174f5d; margin:0px 8px 0 0px;">|</span><a href="<?=APPLICATION_URL?>index/support" id="selected">Support</a> 



                <?php } ?>

                </b>

            </div>

        </div>

       <div style="margin:0 0 0 18px;  display:inline-block;"> 

        <div class="main_outer_div1">

      <?php

	  	//echo "SELECT * , date_add( launch_date, INTERVAL campaign_length DAY ) AS endData FROM ".LAUNCHCAMPAIGN." WHERE campaign_status = '1' AND campaign_category = '1' ORDER BY endData DESC" ; die;

		//echo "SELECT * FROM ".LAUNCHCAMPAIGN." WHERE (campaign_status = '1' AND campaign_category = '1') && (goal=sold)"; die;

		

		//echo count($slid);die;

		//prd($slid);

		//prd($slid);

		if($this->category=='discover')

		{ $slid=$db->runquery("SELECT * FROM ".LAUNCHCAMPAIGN." WHERE sold>=goal and campaign_category='1'");

		foreach($slid as $key=>$value)

				{

					$s=$value['sold']; $g=$value['goal']; @$w=($s/$g)*100; 

		?> <?php $urlPath=urlencode($value['url'])?>

  	 <?php 

		  $k=0; //echo "------------"; die; 

		   $row1=$db->runQuery("select DATE_ADD('".$value['launch_date']."', INTERVAL '".$value['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$value['launch_date']."', INTERVAL -1 DAY) AS prevDate");

														//prd($row1);

														//echo "...launch...".$value['launch_date'];

														//echo $value['campaign_length'];

														//echo "..End..".$enddate=$row1[0]['nextDate'];

														$enddate=$row1[0]['nextDate'];

														$startdate=$value['launch_date'];

														//echo $startdate.'<br/>'; 

														//echo $enddate;

														//prd($enddate);

														$date=date("Y-m-d");

														$newdat2=explode(" ",$enddate);// function breaks string into ARRAY

														$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format

														$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format

														//$this->view->newdat4=$newdat4;

														//prd($enddate);

														$diff = strtotime($enddate) - strtotime(date('Y-m-d H:i:s'));	

														$day_difference = floor($diff / (60*60*24));

													//	if($day_difference<=0)

														{

		  ?>

        <div style="width:305px; height:400px; margin-right:15px; float:left; margin-bottom:30px; background-color:#FFF;">

            <div style="width:287px; padding:8px; height:330px; margin-right:20px;">

                <div style="display:inline-block; width:282px; height:285px;">

                	<a href="<?=APPLICATION_URL.$urlPath?>">

                      <?php if($value['tee_image']!="" )

                                { ?> 

                                <?php if($value['tee_image']!="" and  file_exists(SITE_ROOT.'images/usersdesign/'.$value['tee_image']))

                                {?>

                                <img 

                                data-caman="brightness(10) contrast(30) sepia(60) saturation(-30)"

                                data-caman-hidpi="<?=APPLICATION_URL?>images/usersdesign/<?=$value['tee_image']?>"

                                src="<?=APPLICATION_URL?>images/usersdesign/<?=$value['tee_image']?>" border="0" width="285" height="285" style="margin-left:-50px;">

                                <!--             <img src="<?=APPLICATION_URL?>images/usersdesign/<?=$values['tee_image']?>" border="0" width="285" height="285"  />

                                -->            

                                <?php }

                                else

                                {?> <img  src="<?=IMAGES_URL?>var.png" border="0" width="285" height="285"/>

                                <?php } ?>

                                

                                

                                <?php }else

                                {?> <img  src="<?=IMAGES_URL?>var.png" border="0" width="285" height="285"/>

                                <?php } ?>

                    </a>

                   <!--  <img src="<?=IMAGES_URL?><?=$value['tee_image']?>" width="270" height="318"/>-->

                </div>

                <div  align="left" style="padding:10px 0 0 0; ">

                	<label class="picname">

                    	<a href="<?=APPLICATION_URL.$urlPath?>" style="color:#000000;"><b>

                         <?php echo $value['title']  ?> </b></a>

                    </label>

                    <br />

                    <label class="by"> by  </label>

               <?php

			   $username=$db->runquery("select * from ".USERS." where user_id='".$value['user_id']."'");

			   //prd($username);

			   ?>

                    <label class="authorname">

                       <?php

					    echo $username[0]['public_name'];?>

                    </label>

                </div>

              </div>  

            <div style="width:305px; height:70px; margin-right:20px; margin-bottom:30px;">

                  <div   align="left" style="  background-color:#e4e3e3; border:#cfcfcf solid 5px;">

                            <?php /* if($w<100)

						   { 

							  

						   ?>

                           <div style="width:200px; height:20px; margin-bottom:3px; margin-left:8px;">

                                    	<label style="font-family:'Arial'; font-size:17px; color:#0facfd">

                                           <b>$<?php echo $value['selling_price'] ?></b>

                                        </label>

                                        <label style="font-family:'Arial'; font-size:14px; color:#606060; font-weight:normal;">

                                           <?php echo $value['sold'] ?> of <?php echo $value['goal'] ?> reserved <?php ?>

                                        </label>

                                    </div>

                              <div style="width:95%;height:8px;border:1px solid #319ebc ;border-radius:8px; margin-left:9px; ">

                           			<div align="center" style="height:7px; width:<?=@$w?>%; border-radius:8px;border:1px solid #319ebc ; background-color:#319ebc;">

                                	</div>

                              </div>

                                <?php

						   }

						   else

						   {

							

								?>

                                  

                            			<div style="float:left; height:4px; width:100%;background-color:#fff">&nbsp;</div>

                                        <div style="background-color:#f8f8f8; font-family:Arial, Helvetica, sans-serif; font-weight:400;height:26px; width:100%; margin-top:4px; border-top:2px solid #cdcdcd;border-bottom:3px solid #cdcdcd">

                                        	<div style="float:left; padding-top:0px; padding-left:5px; ">

                                            <span style="color:#6bb03d;font-size:22px;font-weight:bold;">100%</span>&nbsp;

                                            <span style="color:#5f5d5f;font-size:16px;">Funded</span></div>

                                            <div style="float:left; margin-left:18px; padding-left:3px; margin-top:3px; background-color:#e4e3e3; width:auto; color:#0fb1f6; 

                                            font-size:18px; font-weight:bold; height:21px; padding-right:5px;">  <b>$<?php echo $value['selling_price'] ?></b></div>

                                            <a href="<?=APPLICATION_URL.$urlPath?>" >

                                            <div style="float:right; width:82px;font-size:16px; font-weight:600; height:23px; padding-left:6px; padding-top:3px;

                                             background-color:#7d7d7d; color:#ffffff;" id="purchase_error<?=$value['campaign_id']?>">BUY NOW</div>

                                             </a>

                                             <div class="info_textData" id="info_div<?=$value['campaign_id']?>"><p>This Campaign has Ended and you can no longer purchase this Design.</p></div>

                                        

                                        </div>

                                  

                                <?php

						   }*/

						   ?>

                              <?php //if($w<100)

							 

						 if(($value['campaign_status']==0 || $day_difference<=0))					    

						   { 

							  

						   ?>

                         				<div style="float:left; height:4px; width:100%;background-color:#fff">&nbsp;</div>

                                        <div style="background-color:#f8f8f8; font-family:Arial, Helvetica, sans-serif; font-weight:400;height:26px; width:100%; margin-top:4px; border-top:2px solid #cdcdcd;border-bottom:3px solid #cdcdcd">

                                        	<div style="float:left; padding-top:0px; padding-left:5px; ">

                                            <span style="color:#6bb03d;font-size:22px;font-weight:bold;">100%</span>&nbsp;

                                            <span style="color:#5f5d5f;font-size:16px;">Funded</span></div>

                                            <div style="float:left; margin-left:18px; padding-left:3px; margin-top:3px; background-color:#e4e3e3; width:auto; color:#0fb1f6; 

                                            font-size:18px; font-weight:bold; height:21px; padding-right:5px;">  <b>$<?php echo $value['selling_price'] ?></b></div>

                                            <a href="<?=APPLICATION_URL.$urlPath?>" >

                                            <div style="float:right; width:82px;font-size:16px; font-weight:600; height:23px; padding-left:6px; padding-top:3px;

                                             background-color:#7d7d7d; color:#ffffff;" id="purchase_error<?=$value['campaign_id']?>">BUY NOW</div>

                                             </a>

                                             <div class="info_textData" id="info_div<?=$value['campaign_id']?>"><p>This Campaign has Ended and you can no longer purchase this Design.</p></div>

                                        

                                        </div>

                          <!-- <div style="width:200px; height:20px; margin-bottom:3px; margin-left:8px;">

                                    	<label style="font-family:'Arial'; font-size:17px; color:#0facfd">

                                           <b>$<?php echo $value['selling_price'] ?></b>

                                        </label>

                                        <label style="font-family:'Arial'; font-size:14px; color:#606060; font-weight:normal;">

                                           <?php echo $value['sold'] ?> of <?php echo $value['goal'] ?> reserved <?php ?>

                                        </label>

                                    </div>

                              <div style="width:95%;height:8px;border:1px solid #319ebc ;border-radius:8px; margin-left:9px; ">

                           			<div align="center" style="height:7px; width:<?=@$w?>%; border-radius:8px;border:1px solid #319ebc ; background-color:#319ebc;">

                                	</div>

                              </div>-->

                                <?php

						   }

						   else

						   {

							

								?>

                        			<div style="float:left; height:4px; width:100%;background-color:#fff">&nbsp;</div>

                                        <div style="background-color:#f8f8f8; font-family:Arial, Helvetica, sans-serif; font-weight:400;height:26px; width:100%; margin-top:4px; border-top:2px solid #cdcdcd;border-bottom:3px solid #cdcdcd">

                                        	<div style="float:left; padding-top:0px; padding-left:5px; ">

                                            <span style="color:#6bb03d;font-size:22px;font-weight:bold;">100%</span>&nbsp;

                                            <span style="color:#5f5d5f;font-size:16px;">Funded</span></div>

                                            <div style="float:left; margin-left:18px; padding-left:3px; margin-top:3px; background-color:#e4e3e3; width:auto; color:#0fb1f6; 

                                            font-size:18px; font-weight:bold; height:21px; padding-right:5px;">  <b>$<?php echo $value['selling_price'] ?></b></div>

                                            <a href="<?=APPLICATION_URL.$urlPath?>">

                                            <div style="float:right; width:82px;font-size:16px; font-weight:600; height:23px; padding-left:6px; padding-top:3px;

                                             background-color:#31a5ca; color:#ffffff;">BUY NOW</div>

                                             </a>

                                        

                                        </div>

                                  

                                <?php

						   }

						   ?>

                     

                        <div style="margin-top:<?=$marginTop?>px;">

                         <?php  if($day_difference>0)

									 { ?>

                                     <div style="width:13px; height:14px; float:left; margin-left:8px; margin-right:4px;">

                                        <img src="<?=IMAGES_URL?>timerclock.png" />

                                        </div>

                                        

                                        <?php } ?>

                                        <div class="day_hours_div" align="left">

					   

					

					

                         <div class="day_hours_div" align="left">

					   

						<!--<?=$day_difference?> days and <?=$hours?> hours left.-->

                         <?php

				   

				  /* $expireData=$db->runQuery("select * , date_add( launch_date, INTERVAL campaign_length DAY ) AS endData  from ".LAUNCHCAMPAIGN." WHERE campaign_status = '1' AND campaign_category = '1' and campaign_id='".$value['campaign_id']."' ORDER BY endData DESC");*/

				   $today= date('Y-m-d H:i:s');

				   $days=$value['campaign_length'];

				   //echo date('Y-m-d H:i:s', strtotime($value['launch_date']. ' + '.$days.' day'));

				   $totaldate= strtotime((date('Y-m-d H:i:s', strtotime($value['launch_date']. ' + '.$days.' day')))) - (strtotime($today));

				  if($day_difference>0)

									 { 

				   ?>

					   <script type="text/javascript">

                            var start<?=$value['campaign_id']?>=<?=$totaldate?>;

                            start<?=$value['campaign_id']?> = parseFloat(start<?=$value['campaign_id']?>);

                            

                            var end<?=$value['campaign_id']?> = 0 

                            var refresh=1000;

                            if(start<?=$value['campaign_id']?> >= end<?=$value['campaign_id']?> ){

                                

                            mytime<?=$value['campaign_id']?>=setTimeout('display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>)',refresh)

                            }

                            else { window.location.href="<?=APPLICATION_URL?>product/index";}

                            

                            function display_c<?=$value['campaign_id']?>(start1<?=$value['campaign_id']?>){

                            start<?=$value['campaign_id']?> = parseFloat(start1<?=$value['campaign_id']?>);

                            var end<?=$value['campaign_id']?> = 0 

                            var refresh=1000;

                            if(start<?=$value['campaign_id']?> >= end<?=$value['campaign_id']?> ){

                            mytime<?=$value['campaign_id']?>=setTimeout('display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>)',refresh)

                            }

                            else { window.location.href="<?=APPLICATION_URL?>product/index";}

                            }

                            

                            function display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>) {

                                

                            var days<?=$value['campaign_id']?>=Math.floor(start<?=$value['campaign_id']?> / 86400);

                            var hours<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ))/3600)

                            

                            var minutes<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ) - (hours<?=$value['campaign_id']?> *3600 ))/60)

                            

                            var secs<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ) - (hours<?=$value['campaign_id']?> *3600 ) - (minutes<?=$value['campaign_id']?>*60)))

                            

							 minutes<?=$value['campaign_id']?> = ((minutes<?=$value['campaign_id']?>>0) ? ((minutes<?=$value['campaign_id']?>>9) ? minutes<?=$value['campaign_id']?> : '0'+minutes<?=$value['campaign_id']?>) + " " : "");



							 secs<?=$value['campaign_id']?> = ((secs<?=$value['campaign_id']?>>0) ? ((secs<?=$value['campaign_id']?>>9) ? secs<?=$value['campaign_id']?> : '0'+secs<?=$value['campaign_id']?>) + " " : "");

							

							var x<?=$value['campaign_id']?> =days<?=$value['campaign_id']?> + " Days and " + hours<?=$value['campaign_id']?> + " : " + minutes<?=$value['campaign_id']?> + " : " + secs<?=$value['campaign_id']?>+" left" ;

                            

                            document.getElementById('ct_<?=$value['campaign_id']?>').innerHTML = x<?=$value['campaign_id']?>;

                            start<?=$value['campaign_id']?>=start<?=$value['campaign_id']?>- 1;

                            tt<?=$value['campaign_id']?>=display_c<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>);

                            }

                        </script>

                        <?php } 

						else

								{ 	?>   

                                <div align="center" style="width:350px; height:20px;">

                                

                                 <div style="color:#43747F;">This campaign ended on <?=$enddate?></div>

                                <?php  } ?>  

					

                   <div>

                   		<span style="color:#43747F;" id="ct_<?=$value['campaign_id']?>">&nbsp;</span>

                   </div>

                         

						</div>

                        

                        	</div>

					</div>

                         <!--<div style="margin-top:<?=$marginTop?>px;">

                                     <div style="width:13px; height:14px; float:left; margin-left:8px; margin-right:4px;">

                                        <img src="<?=IMAGES_URL?>timerclock.png" />

                                        </div>

                                        <div class="day_hours_div" align="left">

					   

						<!--<?=$day_difference?> days and <?=$hours?> hours left.

               <?php //$date_info=date('Y-m-d H:i:s');

										//echo $date_info; die;

										//if($enddate<$date_info)

										{ ?>

                                        <div style="color:#43747F; font-size:14px;">This campaign ended on <?=$enddate?></div>

                                    </div>

                                    <?php }

                                   // else

									{ ?>

                                      <div style="color:#43747F; font-size:14px;">This campaign ended on <?=$date_info?></div>

                                    </div>-->

                                    <?php } ?>

                         

						</div>

           </div>

            </div>

       </div>

			<script>

            $("#purchase_error"+<?=$value['campaign_id']?>).mouseover(function(e) {

            $("#info_div"+<?=$value['campaign_id']?>).slideDown() ;

            });

            $("#purchase_error"+<?=$value['campaign_id']?>).mouseleave(function(e) {

            $("#info_div"+<?=$value['campaign_id']?>).slideUp() ;

            }); 

            </script>

         <?php } }?>

        <?php

           $k++;

           if($k%3==0)

           {

               ?>

                  <br/>

               <?php

           }

				

		} 

		else if($this->category=='support')

		{ //$slid=$db->runquery("SELECT * FROM ".LAUNCHCAMPAIGN." ");

		

	$slid=$db->runquery("SELECT * FROM ".LAUNCHCAMPAIGN." WHERE sold>=goal and campaign_category='2'"); 

			foreach($slid as $key=>$values)

 				{

					$s=$values['sold']; $g=$values['goal']; @$w=($s/$g)*100;

		  				$k=0;

	     //for($i=0; $i<6; $i++)

		 //{

?>

<?php

$row1=$db->runQuery("select DATE_ADD('".$values['launch_date']."', INTERVAL '".$values['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$values['launch_date']."', INTERVAL -1 DAY) AS prevDate");

										//echo $row1; 

										//echo "...launch...".$values['launch_date']; die;

										//echo $value['campaign_length'];

										//echo "..End..".$enddate=$row1[0]['nextDate'];

										$enddate=$row1[0]['nextDate'];

										$newdat2=explode(" ",$enddate);// function breaks string into ARRAY

										$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format

										$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format

										//$this->view->newdat4=$newdat4;

										$diff = strtotime($enddate) - strtotime(date('Y-m-d H:i:s'));	

										$day_difference = floor($diff / (60*60*24));

										$hours=	$day_difference*24;													

										//echo "............day diffrenc is:".$day_difference; 

										//echo "...........end date is:".$enddate;

										//echo "..........end date is:".$newdat4;

							//	//echo "...........hours is : ".$hours;die;

						//if($day_difference<0)

					 {	

				   ?>    <?php $urlPath=urlencode($values['url'])?>

   <div align="center" class="main_outer_div" style="width:1000px; height:auto; display:inline-block;">

			<div class="tshirt_boxes"><!---Boxes---->

                <div class="tshirt_image"><!--- Division for tshirt images----->

                <a href="<?=APPLICATION_URL.$urlPath?>">

                   <?php if($values['tee_image']!="" )

                                { ?> 

                                <?php if($values['tee_image']!="" and  file_exists(SITE_ROOT.'images/usersdesign/'.$values['tee_image']))

                                {?>

                                <img 

                                data-caman="brightness(10) contrast(30) sepia(60) saturation(-30)"

                                data-caman-hidpi="<?=APPLICATION_URL?>images/usersdesign/<?=$values['tee_image']?>"

                                src="<?=APPLICATION_URL?>images/usersdesign/<?=$values['tee_image']?>" border="0" width="285" height="285" style="margin-left:-50px;">

                                <!--             <img src="<?=APPLICATION_URL?>images/usersdesign/<?=$values['tee_image']?>" border="0" width="285" height="285"  />

                                -->            

                                <?php }

                                else

                                {?> <img  src="<?=IMAGES_URL?>var.png" border="0" width="285" height="285"/>

                                <?php } ?>

                                

                                

                                <?php }else

                                {?> <img  src="<?=IMAGES_URL?>var.png" border="0" width="285" height="285"/>

                                <?php } ?>

                </a>

                </div><!--- End Division for tshirt images----->

                <div class="text_div" style="height:auto; min-height:50px;"><!---Division for text in box---->

                 <div style="float:left"><h6 class="heading_div"><a href="<?=APPLICATION_URL.$urlPath?>" style="color:#2b86a0;"><?php echo $values['title'] ?></a></h6></div>

                <div style="float:right">

                    <label class="by"> by  </label>

               <?php

			   $username=$db->runquery("select * from ".USERS." where user_id='".$values['user_id']."'");

			   //prd($username);

			   ?>

                    <label class="authorname">

                       <a href="<?=APPLICATION_URL?>user/view/user_id/<?=$username[0]['user_id']?>" style="color:#06F">

                        <?php

					    echo $username[0]['public_name'];?>

                        </a>

                    </label>

					</div>	

                </div><!---End Division for text in box---->

                <div class="text_div"><!---Division for text in box---->

             

						<p><?=$values['description']?></p>

                </div>

                     <div style="width:305px; height:70px; margin-left:81px;">

                  <div style="background-color:#e4e3e3; border:#cfcfcf solid 5px; height:63px;">

                  <?php $marginTop==0;	

				  //if($w<100)

						 if(($values['campaign_status']==0 || $day_difference<=0))					    

						   { 

							  

						   ?>

                         				<div style="float:left; height:4px; width:100%;background-color:#fff">&nbsp;</div>

                                        <div style="background-color:#f8f8f8; font-family:Arial, Helvetica, sans-serif; font-weight:400;height:26px; width:100%; margin-top:4px; border-top:2px solid #cdcdcd;border-bottom:3px solid #cdcdcd">

                                        	<div style="float:left; padding-top:0px; padding-left:5px; ">

                                            <span style="color:#6bb03d;font-size:22px;font-weight:bold;">100%</span>&nbsp;

                                            <span style="color:#5f5d5f;font-size:16px;">Funded</span></div>

                                            <div style="float:left; margin-left:18px; padding-left:3px; margin-top:3px; background-color:#e4e3e3; width:auto; color:#0fb1f6; 

                                            font-size:18px; font-weight:bold; height:21px; padding-right:5px;">  <b>$<?php echo $values['selling_price'] ?></b></div>

                                            <a href="<?=APPLICATION_URL.$urlPath?>" >

                                            <div style="float:right; width:82px;font-size:16px; font-weight:600; height:23px; padding-left:6px; padding-top:3px;

                                             background-color:#7d7d7d; color:#ffffff;" id="purchase_error<?=$values['campaign_id']?>">BUY NOW</div>

                                             </a>

                                             <div class="info_textData" id="info_div<?=$values['campaign_id']?>"><p>This Campaign has Ended and you can no longer purchase this Design.</p></div>

                                        

                                        </div>

                      

                                <?php

						   }

						   else

						   {

							

								?>

                        			<div style="float:left; height:4px; width:100%;background-color:#fff">&nbsp;</div>

                                        <div style="background-color:#f8f8f8; font-family:Arial, Helvetica, sans-serif; font-weight:400;height:26px; width:100%; margin-top:4px; border-top:2px solid #cdcdcd;border-bottom:3px solid #cdcdcd">

                                        	<div style="float:left; padding-top:0px; padding-left:5px; ">

                                            <span style="color:#6bb03d;font-size:22px;font-weight:bold;">100%</span>&nbsp;

                                            <span style="color:#5f5d5f;font-size:16px;">Funded</span></div>

                                            <div style="float:left; margin-left:18px; padding-left:3px; margin-top:3px; background-color:#e4e3e3; width:auto; color:#0fb1f6; 

                                            font-size:18px; font-weight:bold; height:21px; padding-right:5px;">  <b>$<?php echo $values['selling_price'] ?></b></div>

                                            <a href="<?=APPLICATION_URL.$urlPath?>">

                                            <div style="float:right; width:82px;font-size:16px; font-weight:600; height:23px; padding-left:6px; padding-top:3px;

                                             background-color:#31a5ca; color:#ffffff;">BUY NOW</div>

                                             </a>

                                        

                                        </div>

                                  

                                <?php

						   }

						 

						  /* {  //echo "JSK".$w;die;

							  $marginTop=22;

						   ?>

      

                                  <div style="width:295px; height:20px; margin-bottom:5px;">

                                  <div class="div_info1"> 

                                     <label style="font-family:'Arial'; font-size:17px; color:#0facfd">

                                         <b style="text-align:left; margin-left:8px;">$<?php echo $values['selling_price'] ?></b>

                                        </label>

                                        </div>

                                        <div class="info_div2">

                                        <label style="font-family:'Arial'; font-size:14px; color:#606060; font-weight:normal; margin-left:10px;">

                                         <?php echo $values['sold']?> of <?php echo $values['goal']; ?> reserved

                                        </label>

                                        </div>

                                    </div>

                              <div style="width:90%;height:8px;border:1px solid #319ebc ;border-radius:8px; float:left; margin-left:10px;">

                           		<div style="height:7px; width:<?=$w?>%; float:left; border-radius:8px;border:1px solid #319ebc ; background-color:#319ebc; ">

                                </div>

                              </div>

                                    

      

      			

                		<?php } 

						else

						{

							$marginTop=6;

                        

							

								?>

                                  

                            			<div style="float:left; height:4px; width:100%;background-color:#fff">&nbsp;</div>

                                        <div style="background-color:#f8f8f8; font-family:Arial, Helvetica, sans-serif; font-weight:400;height:26px; width:100%; margin-top:4px; border-top:2px solid #cdcdcd;border-bottom:3px solid #cdcdcd">

                                        	<div style="float:left; padding-top:0px; padding-left:5px; ">

                                            <span style="color:#6bb03d;font-size:22px;font-weight:bold;">100%</span>&nbsp;

                                            <span style="color:#5f5d5f;font-size:16px;">Funded</span></div>

                                            <div style="float:left; margin-left:18px; padding-left:3px; margin-top:3px; background-color:#e4e3e3; width:auto; color:#0fb1f6; 

                                            font-size:18px; font-weight:bold; height:21px; padding-right:5px;">  <b>$<?php echo $values['selling_price'] ?></b></div>

                                            <a href="<?=APPLICATION_URL.$urlPath?>">

                                            <div style="float:right; width:82px;font-size:16px; font-weight:600; height:23px; padding-left:6px; padding-top:3px;

                                             background-color:#7d7d7d; color:#ffffff;">BUY NOW</div>

                                             </a>

                                        

                                        </div>

                                  

                                <?php

						   

                    	 

						 

						 }*/ ?>

                         

                         <div style="margin-top:<?=$marginTop?>px;">

                         <?php  if($day_difference>0)

									 { ?>

                                     <div style="width:13px; height:14px; float:left; margin-left:8px; margin-right:4px;">

                                        <img src="<?=IMAGES_URL?>timerclock.png" />

                                        </div>

                                        

                                        <?php } ?>

                                        <div class="day_hours_div" align="left">

					   

					

					

                         <div class="day_hours_div" align="left">

					   

						<!--<?=$day_difference?> days and <?=$hours?> hours left.-->

                         <?php

				   

				  /* $expireData=$db->runQuery("select * , date_add( launch_date, INTERVAL campaign_length DAY ) AS endData  from ".LAUNCHCAMPAIGN." WHERE campaign_status = '1' AND campaign_category = '1' and campaign_id='".$values['campaign_id']."' ORDER BY endData DESC");*/

				   $today= date('Y-m-d H:i:s');

				   $days=$values['campaign_length'];

				   //echo date('Y-m-d H:i:s', strtotime($values['launch_date']. ' + '.$days.' day'));

				   $totaldate= strtotime((date('Y-m-d H:i:s', strtotime($values['launch_date']. ' + '.$days.' day')))) - (strtotime($today));

				  if($day_difference>0)

									 { 

				   ?>

					   <script type="text/javascript">

                            var start<?=$values['campaign_id']?>=<?=$totaldate?>;

                            start<?=$values['campaign_id']?> = parseFloat(start<?=$values['campaign_id']?>);

                            

                            var end<?=$values['campaign_id']?> = 0 

                            var refresh=1000;

                            if(start<?=$values['campaign_id']?> >= end<?=$values['campaign_id']?> ){

                                

                            mytime<?=$values['campaign_id']?>=setTimeout('display_ct_<?=$values['campaign_id']?>(start<?=$values['campaign_id']?>)',refresh)

                            }

                            else { window.location.href="<?=APPLICATION_URL?>product/index";}

                            

                            function display_c<?=$values['campaign_id']?>(start1<?=$values['campaign_id']?>){

                            start<?=$values['campaign_id']?> = parseFloat(start1<?=$values['campaign_id']?>);

                            var end<?=$values['campaign_id']?> = 0 

                            var refresh=1000;

                            if(start<?=$values['campaign_id']?> >= end<?=$values['campaign_id']?> ){

                            mytime<?=$values['campaign_id']?>=setTimeout('display_ct_<?=$values['campaign_id']?>(start<?=$values['campaign_id']?>)',refresh)

                            }

                            else { window.location.href="<?=APPLICATION_URL?>product/index";}

                            }

                            

                            function display_ct_<?=$values['campaign_id']?>(start<?=$values['campaign_id']?>) {

                                

                            var days<?=$values['campaign_id']?>=Math.floor(start<?=$values['campaign_id']?> / 86400);

                            var hours<?=$values['campaign_id']?> = Math.floor((start<?=$values['campaign_id']?> - (days<?=$values['campaign_id']?> * 86400 ))/3600)

                            

                            var minutes<?=$values['campaign_id']?> = Math.floor((start<?=$values['campaign_id']?> - (days<?=$values['campaign_id']?> * 86400 ) - (hours<?=$values['campaign_id']?> *3600 ))/60)

                            

                            var secs<?=$values['campaign_id']?> = Math.floor((start<?=$values['campaign_id']?> - (days<?=$values['campaign_id']?> * 86400 ) - (hours<?=$values['campaign_id']?> *3600 ) - (minutes<?=$values['campaign_id']?>*60)))

                            

							 minutes<?=$values['campaign_id']?> = ((minutes<?=$values['campaign_id']?>>0) ? ((minutes<?=$values['campaign_id']?>>9) ? minutes<?=$values['campaign_id']?> : '0'+minutes<?=$values['campaign_id']?>) + " " : "");



							 secs<?=$values['campaign_id']?> = ((secs<?=$values['campaign_id']?>>0) ? ((secs<?=$values['campaign_id']?>>9) ? secs<?=$values['campaign_id']?> : '0'+secs<?=$values['campaign_id']?>) + " " : "");

							

							var x<?=$values['campaign_id']?> =days<?=$values['campaign_id']?> + " Days and " + hours<?=$values['campaign_id']?> + " : " + minutes<?=$values['campaign_id']?> + " : " + secs<?=$values['campaign_id']?>+" left" ;

                            

                            document.getElementById('ct_<?=$values['campaign_id']?>').innerHTML = x<?=$values['campaign_id']?>;

                            start<?=$values['campaign_id']?>=start<?=$values['campaign_id']?>- 1;

                            tt<?=$values['campaign_id']?>=display_c<?=$values['campaign_id']?>(start<?=$values['campaign_id']?>);

                            }

                        </script>

                        <?php } 

						else

								{ 	?>   

                                <div align="center" style="width:350px; height:20px;">

                                

                                 <div style="color:#43747F;">This campaign ended on <?=$enddate?></div>

                                <?php  } ?>  

					

                   <div>

                   		<span style="color:#43747F;" id="ct_<?=$values['campaign_id']?>">&nbsp;</span>

                   </div>

                         

						</div>

                        

                        	</div>

					</div>

                         <!--<div style="margin-top:<?=$marginTop?>px;">

                                     <div style="width:13px; height:14px; float:left; margin-left:8px; margin-right:4px;">

                                        <img src="<?=IMAGES_URL?>timerclock.png" />

                                        </div>

                                        <div class="day_hours_div" align="left">

					   

						<!--<?=$day_difference?> days and <?=$hours?> hours left.

               <?php //$date_info=date('Y-m-d H:i:s');

										//echo $date_info; die;

										//if($enddate<$date_info)

										{ ?>

                                        <div style="color:#43747F; font-size:14px;">This campaign ended on <?=$enddate?></div>

                                    </div>

                                    <?php }

                                   // else

									{ ?>

                                      <div style="color:#43747F; font-size:14px;">This campaign ended on <?=$date_info?></div>

                                    </div>-->

                                    <?php } ?>

                         

						</div>

					</div>

           </div>

            </div>  

         <div class="side_box" style="width:250px; height:38px; background:url(<?=IMAGES_URL?>side_box_gradient.png) repeat-x; float:right; margin-top:-102px; margin-right:13px;">

                <img src="<?=IMAGES_URL?>image1.png" align="right" style="margin-top:4px; margin-right:8px;" />

                 <!-- <a href="<?=APPLICATION_URL?><?=$value['url']?>"> 

            <img src="<?=IMAGES_URL?>image1.png" align="right" style="margin-top:3px; margin-right:3px;" />

                  </a>--> 

                <p style="font-family:'Cambria'; font-size:20px; color:#FFFFFF; text-align:left; margin:7px 0 13px 20px; text-shadow: -1px -1px #267183;">

               

                <a href="<?=APPLICATION_URL.$urlPath?>" style="color:#FFF">View this campaign</a></p>

         </div>

      </div>

      <?php } 

		

	  

	   }?>

            </div>

            

            <?php }?>

        </div>

      </div>

    </div>

</div>

<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>-->