<?php
//error_log('edit.phtml: '.print_r($this->data, true));
?>
<script type="text/javascript" src="<?=APPLICATION_URL?>tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
	// O2k7 skin (silver)
	tinyMCE.init({
		// General options
		mode : "exact",
		elements : "description",
		theme : "advanced",
		relative_urls : false,
		skin : "o2k7",
		skin_variant : "black",
		plugins : "layer,table,save,advhr,advimage,advlink,emotions,noneditable,template",

		// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontselect,fontsizeselect",
		
		theme_advanced_buttons2 : "forecolor,backcolor",
		
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true	
	});
</script>
<div>
   <form method="post" action="<?=$this->url(array('controller'=>'launchcampaign', 'action'=>'updateedited', 'cid'=>$this->cid), 'default', true)?>">
<div style="width:1000px; height:auto; clear:both;">
   		<div align="left" style="width:1000px; font-family:Calibri; font-size:30px; color:#333333;">
        	<b>	Edit Details of '<?=$this->data[0]['title']?>' </b><br />
                 <hr style="width:980px; color:#999;" align="left"/>
        </div>
    <?=$this->myform->url?>
    
    <div align="left" style="width:580px; height:auto; float:left;">
    	    
        <div style="width:560px; height:80px;"> 
      	
             
                <div align="left" style="width:540px; height:120px; margin-top:10px;">
               
             
                   <div class="editcamp">
                        <b> Campaign Title </b>

                    </div>
          
          <div style="width:540px; height:10px;">
            
          </div>
                    
                    <div style="width:540px;">
                         <?=$this->myform->camptitle?>
                    </div>
           
            <div style="width:540px; height:10px;">
                
            </div>
                   

        </div>
      </div>
        
               
   
     <div align="left" style="width:540px; height:250px;">
     
            
            <div class="editcamp">
            	<b> Description </b>
            </div>
 
                    <div style="width:540px; height:10px;">
                    </div>
           
           <div style="width:540px;">
            	 <?=$this->myform->description?>
           </div>
   
    
        </div>
    
    
  <!--  <div align="left" style="width:540px; height:auto;">
              
                          <div style="width:540px; height:10px;">  
                          </div>
                    
                    <div style="width:540px; font-family:Tahoma; color:#20a762; font-size:14px;">
                        
                          <?=$this->myform->shippingaddr?>
                          Allow buyers to pick-up their orders from you (pickup shipping is free).
                    </div>
           
                            <div style="width:540px; height:10px;">
                            </div>
             
         
          
                      
                      <div id="addressdiv" style="display:none; width:540px; height:auto; font-family:Tahoma; color:#045725; font-size:14px;">
                      		
                            <div style="width:5px; height:450px; float:left;">
                            </div>
                       
                              <div style="width:540px; font-family:Tahoma; color:#20a762; font-size:14px;">
                              		Where/when will buyers be able to pick-up their shirts?
                              </div>
                              
                              <div>
                              	 <?=$this->myform->instruction?>
                              </div>
                              
                               <div style="width:540px; font-family:Tahoma; color:#333; font-size:14px;">
                              		Buyers will see these instructions when choosing between shipping/pick-up
                              </div>
                              
                            	<div style="margin-top:5px;">
                                   <label class="myaccsubtitles">First Name</label>
                                </div>
                                
                                 <div style="margin-top:5px;">
                                      <?=$this->myform->firstname?>
                                   </div>
                                   
                                  <div style="margin-top:5px;">
                                   <label class="myaccsubtitles">Last Name</label>
                                </div>
                                
                                 <div style="margin-top:5px;">
                                      <?=$this->myform->lastname?>
                                   </div>
                                   
                                
                               <div style="margin-top:5px">
                                     <label class="myaccsubtitles">Address</label>
                               </div>
                   
                                <div style="margin-top:5px;">
                                    <?=$this->myform->newaddress?>
                               </div>
                
                               
                    
                               <div style="margin-top:5px;">
                                    <div style="float:left; width:120px">
                                        <label class="myaccsubtitles">City</label>
                                     </div>
                                     <div style="float:left; margin-top:2px; width:120px">
                                        <label class="myaccsubtitles">State</label>
                                     </div>
                                    <div>
                                        <label class="myaccsubtitles">Zipcode</label>
                                     </div>
                               </div>
                   
                               <div style="margin-top:5px;">
                                    <div style="float:left; width:120px">
                                         <?=$this->myform->newcity?>
                                    </div>
                                    
                                    <div style="float:left; width:120px;">
                                         <?=$this->myform->newstate?>
                                    </div>
                                    
                                    <div>
                                         <?=$this->myform->newzipcode?>
                                    </div>
                               </div>
                               
                              
                               
                               <div style="width:500px; height:10px;">
                               </div>
                   
                      </div>
                  
               </div>-->
               
               	<div style="width:550px; height:10px;">
                </div>
       
        <div style="padding-bottom:20px;"> 
                <div style="width:560px; height:9px;">
                </div>
                       <div align="left">        
                           	<input type="submit" name="submit" value="Save Changes" class="accbutton" />
                            &nbsp;
                  		<a href="<?=APPLICATION_URL?>myaccount/activecampaign" style="text-decoration:none;"> 
                             <input type="button" name="button" value="Cancel" class="accbutton" />
                        </a>
                       </div>
               </div>
        </div>
 </div>
  <!-- ----------t shirt image ------------- -->  
    
     <div style="width:400px; height:600px; float:left;">
         <div id="front_i" style="width:400px; height:550px;position:absolute;display:block;">
        	<img src="<?=IMAGES_URL?>/usersdesign/<?php echo $this->data[0]['tee_image']; ?>"  />
         </div>
         <div id="back_i" style="width:400px; height:550px;position:absolute;display:none;">
            <img src="<?=IMAGES_URL?>/usersdesign/<?php echo $this->data[0]['tee_back_image']; ?>"  />
         </div>
         <div align="center" style="width:400px;height:20px; font-family:Calibri; font-size:18px; color:#0099CC;position:absolute;margin-top:550px;">
            <span onclick="showtee();" style="cursor:pointer;">front</span>/<span  onclick="showtee1();" style="cursor:pointer;">back</span>
         </div>
    </div>
            <div style="width:1000px; height:10px;">
            </div>
 </form>      
</div>
</div>
<script type="text/javascript">
<?php if(array_key_exists('shippingaddr', $_REQUEST) && $_REQUEST['shippingaddr']==1): ?>
	document.getElementById('addressdiv').style.display="block";
<?php endif; ?>

</script>
<script type="text/javascript">
function opendiv(obj1)
{
 if( document.getElementById('obj1').checked==true)
 {
  document.getElementById('addressdiv').style.display="block";
 }
 else
 {
  document.getElementById('addressdiv').style.display="none"; 
 }
}


function showtee()
{
	document.getElementById('front_i').style.display='block'
	document.getElementById('back_i').style.display='none';
}

			
function showtee1()
{
	document.getElementById('front_i').style.display='none'
	document.getElementById('back_i').style.display='block';
}	

</script>