<div style="width:700px;" style="float:left">

	<div style="width:700px; float:left">
    
        <div style="margin-left:10px; margin-top:10px; margin-bottom:30px; float:left; width:500px">
        	<label class="myaccheading">Email Friends<br /></label>
            
            <hr style="width:500px; color:#999;" align="left"/>
           
           <div>
               <form method="post" action="<?=$this->url(array('controller'=>'launchcampaign', 'action'=>'emailit'), 'default', true)?>">
                  
                   <div style="margin-top:10px">
                   	  <label class="myaccsubtitles">From (Your Email ID)</label>
                   </div>
                   
                   <div style="margin-top:5px;">
                   	  <?=$this->myform->emailid?>
                   </div>
                   
                    <div style="margin-top:10px">
                   		 <label class="myaccsubtitles">To (Friends Email ID)</label>
                   </div>
                   
                    <div style="margin-top:5px;">
                     	<?=$this->myform->friendsemailid?>
                   </div>
                
                
                   <div style="margin-top:10px">
                   		 <label class="myaccsubtitles">Subject</label>
                   </div>
                   
                    <div style="margin-top:5px;">
                     	<?=$this->myform->subject?>
                   </div>
                
                    
                <div style="margin-top:10px">
                   		 <label class="myaccsubtitles">Content</label>
                   </div>
                   
                    <div style="margin-top:5px;">
                     	<?=$this->myform->content?>
                   </div>
                
                
                 
                 <div style="margin-top:20px;">
                 	<input type="submit" name="submit" id="submit" value="Send Email" class="accbutton">
      <a href="<?=APPLICATION_URL?>myaccount/profile" style="text-decoration:none;"> <input type="button" name="cancel" id="cancel" value="Cancel" class="accbutton"> </a>
                 </div>
                   
                    
          
               </form>
                
           </div>
           
        </div>
        
    </div>


</div>


