<div class="mws-panel grid_10">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1"><?=$this->pageHeading?></span>
    </div>
    <div class="mws-panel-body">
        <div class="mws-panel-toolbar top clearfix ">
            <ul>
                <li><a class="mws-ic-16 ic-cross" href="javascript:void(0)" title="Delete" onclick="deleteitem()">Delete</a></li>
            </ul>
        </div>
        <!--<table class="mws-table">-->
         <table class="mws-datatable-fn mws-table">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th><input type="checkbox" name="deletebcchk" id="deletebcchk" onclick="return checkall(this)" /></th>


                    <th>Campaign Title</th>

                     <th>Campaign Status(1=Active/0=Ended)</th>

                     <th>View</th>

                      <th>Status</th>     <!-- For Enablr disable -->

                      <th>Slider View</th>

                     <!--<th width="10%">Edit</th>-->
                </tr>
            </thead>
            <tbody>
             <?php
					for($i=0;$i<count($this->sql);$i++)
					{
					?>

                <?php
                    //$start++;
                    /*if($this->sql[$i]['admin_status']==1){ $image ='tick.png';  }
                    if($this->sql[$i]['admin_status']==0){ $image ='cross.png';  } */
                    if($cClass=="gradeX odd")
                        {$cClass="gradeX even";}
                    else
                        {$cClass="gradeX odd";}
                    ?>
                        <tr class="gradeX">
                            <td><?=$i+1;?></td>
                            <td>
                                <input name='check<?=$i;?>' id='check<?=$i+1;?>' value='<?=$this->sql[$i]['campaign_id'];?>'
                                    onchange='return check_check("bcdel","deletebcchk")' type='checkbox'>
                                <script>
                                    $('#bcdel').html(''); document.getElementById('deletebcchk').checked = false;
                                </script>
                            </td>


                            <td> <?=$this->sql[$i]['title']?></td>
                            <td> <?=$this->sql[$i]['campaign_status']?></td>

                         <td> <a href="<?=APPLICATION_URL_ADMIN?>campaign/view/campid/<?=$this->sql[$i]['campaign_id']?>">
          					 <!-- <img src="<?=APPLICATION_URL_ADMIN;?>css/icons/16/edit.png" border='0' />-->
                             <img src="<?=IMAGES_URL_ADMIN?>previewicon.png" width="20" height="10" >
            				  </a>
                         </td>


                            <td>
                       <a href="<?=APPLICATION_URL_ADMIN?>campaign/changestatus/campId/<?=$this->sql[$i]['campaign_id']?>/Status/<?=$this->sql[$i]['admin_status']?>">
                                   <?php
		   				if($this->sql[$i]['admin_status']==1)
		   				{
			   			$status=$this->sql[$i]['admin_status'];
						 ?>
              			<img src=<?=IMAGES_URL_ADMIN?>tick.gif onClick="f1('<?=$this->sql[$i]['admin_status']?>','<?= $status?>')" />
			   			 <?php
							}
							if($this->sql[$i]['admin_status']==0)
							{
								$status=$this->sql[$i]['admin_status'];
						 ?>
                 		 <img src=<?=IMAGES_URL_ADMIN?>cross.png onClick="f1('<?=$this->sql[$i]['admin_status']?>','<?= $status?>')" />
                 		 <?php
		    			}
									?>
          				 </a>
                            </td>



                             <td>
                       <a href="<?=APPLICATION_URL_ADMIN?>campaign/sliderstatus/campId/<?=$this->sql[$i]['campaign_id']?>/Status/<?=$this->sql[$i]['slider_status']?>">
                                   <?php
		   				if($this->sql[$i]['slider_status']==1)
		   				{
			   			$status=$this->sql[$i]['slider_status'];
						 ?>
              			<img src=<?=IMAGES_URL_ADMIN?>tick.gif onClick="f1('<?=$this->sql[$i]['slider_status']?>','<?= $status?>')" />
			   			 <?php
							}
							if($this->sql[$i]['slider_status']==0)
							{
								$status=$this->sql[$i]['slider_status'];
						 ?>
                 		 <img src=<?=IMAGES_URL_ADMIN?>cross.png onClick="f1('<?=$this->sql[$i]['slider_status']?>','<?= $status?>')" />
                 		 <?php
		    			}
									?>
          				 </a>
                            </td>


                        </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </div>
</div>
<script>
function deleteitem()
{
	var r= "";
	var s="";
	var selected=false;
	for(var i=1;document.getElementById('check'+i);i++){
		if(document.getElementById('check'+i).checked==true){
			r += document.getElementById('check'+i).value+"|";
			selected = true;
		}
	}

	r += '0';
	if(selected){
		var confirmation = confirm("Are you sure want to delete ?");
		if(confirmation!=true){
			return false;
		}

		$.ajax({ url: "<?=APPLICATION_URL_ADMIN."campaign/deletecamp"?>",
		type: "POST",
		data: ({Id:r}),
		success: function(data){
		//alert(data);
			 window.location.href=window.location.href;
		}});
	} else {
		alert('Please choose a record to delete.');
	}
}
function changestatus(Id,Status)
{
    $.ajax({
				type: "POST",
				url: "<?=APPLICATION_URL_ADMIN?>campaign/changestatus",
				data: ({Id:Id,Status:Status}),
				cache: false,
				success: function(data){
				  window.location.href=window.location.href;
			    }
		  });
}

function checkall(thisid)
{
  for(var i=1;document.getElementById('check'+i);i++)
  	{
  		if(document.getElementById(thisid.id).checked==true){document.getElementById('check'+i).checked = true;}
  		if(document.getElementById(thisid.id).checked==false){document.getElementById('check'+i).checked = false;}
	}
}
</script>