<?php	
global $mySession;
$db=new Db();
?>


    <div>
        <span style="font-size:24px; font-weight:800; color:#000"><?=$this->pageHeading?></span>
    </div>

        
       <div style="height:50px">&nbsp;</div>
       <form method="post" name="login" action="<?=$this->url(array('controller'=>'campaign', 'action'=>'saveprofit','id'=>$this->id), 'default', true)?>">
         <table cellpadding="0" cellspacing="0" border="0">
           <tr>
           
           <td style="font-weight:400">Profit:</td>
           
           <td>
                     <input type="text" name="profit" id="profit" style="width:250px" />
           </td>
           </tr> 
           
           <tr><td><input type="submit" name="submit" id="submit" value="Save"  /></td></tr>
                     
        </table>
        </form>
    </div>    	
</div>
