<?php
global $mySession;
$db=new Db();

?>

<script type="text/javascript" src="<?=APPLICATION_URL?>js/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<script type="text/javascript" src="<?=APPLICATION_URL?>js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL?>js/fancybox/jquery.fancybox-1.3.4.css" media="screen" />


<div class="mws-panel grid_right">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1"><?=$this->pageHeading?></span>
    </div>
    <div class="mws-panel-body">
        <div class="mws-panel-toolbar top clearfix ">
            <ul>
                <li><a class="mws-ic-16 ic-cross" href="javascript:void(0)" title="Delete" onclick="deleteitem()">Delete</a></li>
            </ul>
        </div>
        <!--<table class="mws-table">-->
         <table class="mws-datatable-fn mws-table">
            <thead>
                <tr>
                    <th width="10%">S.No</th>
                    <th><input type="checkbox" name="deletebcchk" id="deletebcchk" onclick="return checkall(this)" /></th>


                    <th>Campaign Title</th>

                     <th>Sold / Goal</th>

                      <th>Creator Email ID</th>

                     <th>Email</th>

                     <th>Total</th>
                     <th>Payout</th>
                    <!-- <th>Profit%</th>-->
                  	 <th>Profit</th>
                         <th>View Buyers</th>
                       <th>View Campaign</th>

                      <th>Status</th>     <!-- For Enablr disable -->

                      <th>Slider View</th>

                        <th>Order Processed</th>
                   <th>Download Custom Image</th>
				<th>Creator's share</th>
				<th>Cancelled preapprovals</th>
                     <!--<th width="10%">Edit</th>-->
                </tr>
            </thead>
            <tbody>
             <?php



					for($i=0;$i<count($this->sql);$i++)
					{

						$s=$this->sql[$i]['sold']; $g=$this->sql[$i]['goal']; @$w=($s/$g)*100;
						$row1=$db->runQuery("select DATE_ADD('".$this->sql[$i]['launch_date']."', INTERVAL '".$this->sql[$i]['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$this->sql[$i]['launch_date']."', INTERVAL -1 DAY) AS prevDate");
														//prd($row1);
														//echo "...launch...".$value['launch_date'];
														//echo $value['campaign_length'];
														//echo "..End..".$enddate=$row1[0]['nextDate'];
														$enddate=$row1[0]['nextDate'];
														$startdate=$this->sql[$i]['launch_date'];
														//echo $startdate.'<br/>';
														//echo $enddate;
														//prd($enddate);
														$date=date("Y-m-d");
														$newdat2=explode(" ",$enddate);// function breaks string into ARRAY
														$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format
														$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format
														//$this->view->newdat4=$newdat4;
														//prd($enddate);
														$diff = strtotime($enddate) - strtotime(date('Y-m-d H:i:s'));
														$day_difference = floor($diff / (60*60*24));
							if($day_difference<=0)
					{
					?>


                    <script type="text/javascript">

$(document).ready(function() {

				$("#profit<?=$i?>").fancybox({
				'transitionIn'		: 'elastic',
				'transitionOut'		: 'elastic',
				'opacity'			: true,
				'overlayShow'		: true,
				'overlayColor'		: '#666',
				'overlayOpacity'	: 0.2,
				'scrolling'			:false,
				'easingIn' 			: 'swing',
				'easingOut' 		: 'swing',
				'autoDimensions'    : false,
				'width'				: '60%',
				'height'			: '40%',
				'autoScale'			: true,
				'type'				: 'iframe',
				'speedIn'		:	500,
				'speedOut'		:	600
			});

		});
</script>




                <?php
                    $cClass="gradeX odd";
                    //$start++;
                    /*if($this->sql[$i]['admin_status']==1){ $image ='tick.png';  }
                    if($this->sql[$i]['admin_status']==0){ $image ='cross.png';  } */
                    if($cClass=="gradeX odd")
                        {$cClass="gradeX even";}
                    else
                        {$cClass="gradeX odd";}
                    ?>
                        <tr class="<?php echo $cClass; ?>">
                            <td><?=$i+1;?></td>
                            <td>
                                <input name='check<?=$i;?>' id='check<?=$i+1;?>' value='<?=$this->sql[$i]['campaign_id'];?>'
                                    onchange='return check_check("bcdel","deletebcchk")' type='checkbox'>
                                <script>
                                    $('#bcdel').html(''); document.getElementById('deletebcchk').checked = false;
                                </script>
                            </td>


                            <td> <?=$this->sql[$i]['title']?></td>


                            <td>

                         <?php echo $this->sql[$i]['sold'] ?> / <?php echo $this->sql[$i]['goal'] ?>

                            </td>

                              <?php
					   $data=$db->runquery("SELECT * FROM  ".USERS." WHERE user_id='".$this->sql[$i]['user_id']."'");
					          ?>

                             <td><?=$data[0]['emailid']?></td>
                       <?php
					   $quremailid=$db->runquery("SELECT * FROM  ".ORDER_RECORD." WHERE teeurl='".$this->sql[$i]['url']."'");

					   if($quremailid!="" and count($quremailid)>0)
						{
					   ?>

                       <td>

                       	   <a style="text-decoration:none;" href="<?=APPLICATION_URL_ADMIN?>campaign/emailfriends/name/<?=$this->sql[$i]['url']?>">

                               		Send Thank You
                              </a>

                       </td>
                       <?php
					}
					else
					{
						?>
                        <td>
                       No Buyers
                       </td>
                        <?php
					}
					   ?>


                         <?php
						  		$sp=$this->sql[$i]['selling_price'];
								//echo $sp;

								$total=$this->sql[$i]['sold']*$sp ;
								//echo $total;
						  	 //	echo $sp;

								$differc= $sp-$this->sql[$i]['base_price'];

							//	echo $differc;
								//echo $this->sql[$i]['sold'];
								$payout=$differc*$this->sql[$i]['sold'];

								$profirper=($payout/$total)*100;
								$payout_amount=$total-$payout;
								$x=number_format($profirper, 2, '.', '');
						  ?>

                             <td>  <?=$total?>  </td>
                             <td>  <?php

							 echo $payout?> </td>
                             <!--<td>  <?$x?>% </td> -->
                             <td>
                             <?php
							 if($this->sql[$i]['profit']=="0")
							 {
							 ?>
                             <a href="<?=APPLICATION_URL_ADMIN?>campaign/profit/id/<?=$this->sql[$i]['campaign_id']?>" id="profit<?=$i?>">
                             <img src="<?=IMAGES_URL_ADMIN?>edit.png"  />
                             </a> <?$payout_amount?>
                             <?php
							 }
							 else
							 {
								echo $this->sql[$i]['profit'];
							 }
							 ?>
                              </td>



                       <td>
                       	<a onclick="return popitup('<?=APPLICATION_URL_ADMIN?>campaign/orderrecords/name/<?=$this->sql[$i]['url']?>')" href="<?=APPLICATION_URL?>campaign/orderrecords/name/<?=$this->sql[$i]['url']?>">

                             <img src="<?=IMAGES_URL_ADMIN?>previewicon.png" width="20" height="10" >
            				  </a>
                       </td>
                          <td>
                <a onclick="return popitup('<?=APPLICATION_URL?><?=$this->sql[$i]['url']?>')" href="<?=APPLICATION_URL?><?=$this->sql[$i]['url']?>">
                 <img src="<?=IMAGES_URL_ADMIN?>previewicon.png" width="20" height="10" >
                 </a>
                </td>

                      <?php /*?>   <td> <a href="<?=APPLICATION_URL_ADMIN?>campaign/view/campid/<?=$this->sql[$i]['campaign_id']?>">
          					 <!-- <img src="<?=APPLICATION_URL_ADMIN;?>css/icons/16/edit.png" border='0' />-->
                             <img src="<?=IMAGES_URL_ADMIN?>previewicon.png" width="20" height="10" >
            				  </a>
                         </td><?php */?>


                            <td>
                       <a href="<?=APPLICATION_URL_ADMIN?>campaign/changestatus/campId/<?=$this->sql[$i]['campaign_id']?>/Status/<?=$this->sql[$i]['admin_status']?>">
                                   <?php
		   				if($this->sql[$i]['admin_status']==1)
		   				{
			   			$status=$this->sql[$i]['admin_status'];
						 ?>
              			<img src=<?=IMAGES_URL_ADMIN?>tick.gif onClick="f1('<?=$this->sql[$i]['admin_status']?>','<?= $status?>')" />
			   			 <?php
							}
							if($this->sql[$i]['admin_status']==0)
							{
								$status=$this->sql[$i]['admin_status'];
						 ?>
                 		 <img src=<?=IMAGES_URL_ADMIN?>cross.png onClick="f1('<?=$this->sql[$i]['admin_status']?>','<?= $status?>')" />
                 		 <?php
		    			}
									?>
          				 </a>
                            </td>



                             <td>
                       <a href="<?=APPLICATION_URL_ADMIN?>campaign/sliderstatus/campId/<?=$this->sql[$i]['campaign_id']?>/Status/<?=$this->sql[$i]['slider_status']?>">
                                   <?php
		   				if($this->sql[$i]['slider_status']==1)
		   				{
			   			$status=$this->sql[$i]['slider_status'];
						 ?>
              			<img src=<?=IMAGES_URL_ADMIN?>tick.gif onClick="f1('<?=$this->sql[$i]['slider_status']?>','<?= $status?>')" />
			   			 <?php
							}
							if($this->sql[$i]['slider_status']==0)
							{
								$status=$this->sql[$i]['slider_status'];
						 ?>
                 		 <img src=<?=IMAGES_URL_ADMIN?>cross.png onClick="f1('<?=$this->sql[$i]['slider_status']?>','<?= $status?>')" />
                 		 <?php
		    			}
									?>
          				 </a>
                            </td>


                              <td>
                       <a href="<?=APPLICATION_URL_ADMIN?>campaign/processorder/campId/<?=$this->sql[$i]['campaign_id']?>/Status/<?=$this->sql[$i]['order_process']?>">
                                   <?php
		   				if($this->sql[$i]['order_process']==1)
		   				{
			   			$status=$this->sql[$i]['order_process'];
						 ?>
              			<img src=<?=IMAGES_URL_ADMIN?>tick.gif onClick="f1('<?=$this->sql[$i]['order_process']?>','<?= $status?>')" />
			   			 <?php
							}
							if($this->sql[$i]['order_process']==0)
							{
								$status=$this->sql[$i]['order_process'];
						 ?>
                 		 <img src=<?=IMAGES_URL_ADMIN?>cross.png onClick="f1('<?=$this->sql[$i]['order_process']?>','<?= $status?>')" />
                 		 <?php
		    			}
									?>
          				 </a>
                            </td>
                            <td>
					 <?php if($this->sql[$i]['customimage']!='')	{?>
					<a href="<?=APPLICATION_URL?>images/customimage/<?=$this->sql[$i]['customimage']?>" title="<?=$this->sql[$i]['customimage']?>" download="<?=$this->sql[$i]['url']?>_<?=$this->sql[$i]['customimage']?>" >
    						<img src="<?=IMAGES_URL_ADMIN?>download.jpg" width="20" height="20"  alt="<?=$this->sql[$i]['customimage']?>">
					</a>

					<?php } else { echo "No Custom Image Used"; } ?>

				</td>
<td>$
	<?php echo number_format($this->sql[$i]['ushare'], 2);?>
</td>
<td>
	<?php echo $this->sql[$i]['ucancelled'];?>
</td>

                        </tr>
                    <?php
					}
                }
                ?>
            </tbody>
        </table>
    </div>
</div>
<script>


function popitup(url) {
	newwindow=window.open(url,'name','height=700,width=900,scrollbars=1');
	if (window.focus) {newwindow.focus()}
	return false;
}



function deleteitem()
{
	var r= "";
	var s="";
	var selected=false;
	for(var i=1;document.getElementById('check'+i);i++){
		if(document.getElementById('check'+i).checked==true){
			r += document.getElementById('check'+i).value+"|";
			selected = true;
		}
	}

	r += '0';
	if(selected){
		var confirmation = confirm("Are you sure want to delete ?");
		if(confirmation!=true){
			return false;
		}

		$.ajax({ url: "<?=APPLICATION_URL_ADMIN."campaign/deletecamp"?>",
		type: "POST",
		data: ({Id:r}),
		success: function(data){
		//alert(data);
			 window.location.href=window.location.href;
		}});
	} else {
		alert('Please choose a record to delete.');
	}
}
function changestatus(Id,Status)
{
    $.ajax({
				type: "POST",
				url: "<?=APPLICATION_URL_ADMIN?>campaign/changestatus",
				data: ({Id:Id,Status:Status}),
				cache: false,
				success: function(data){
				  window.location.href=window.location.href;
			    }
		  });
}

function checkall(thisid)
{
  for(var i=1;document.getElementById('check'+i);i++)
  	{
  		if(document.getElementById(thisid.id).checked==true){document.getElementById('check'+i).checked = true;}
  		if(document.getElementById(thisid.id).checked==false){document.getElementById('check'+i).checked = false;}
	}
}
</script>
