 <div align="center" style="width:100%; background-image:url(<?=IMAGES_URL?>footercolor.png); background-repeat:repeat-x; height:115px;">

         

         <div style="width:1000px;">

                            

                       <div style="height:20px; width:1000px;">

                            <div align="left" style="float:left; width:480px; height:20px;">

                                <label style="font-family:Calibri; color:#0dd25c; font-size:18px;">

                                    TeeshirtSCRIPT T-shirts </label><label style="font-family:Calibri; font-size:15px; color:#cccaca;"> allows you to crowdfund awesome custom apparel.

                                </label>

                            </div>

                            

                             <div align="right" style="margin-top:7px; white-space:nowrap; width:500px; height:20px; float:right;">

                               

                                <div align="center" style="float:left; margin-top:0px; width:50px;">

                                    <label class="footertext">

                                        <a  href="<?=APPLICATION_URL?>about/index/page/faq">FAQ</a>

                                    </label>

                                </div>

                                

                               <div style="float:left; width:80px;" align="center">

                                    <label class="footertext">

                                        <a href="<?=APPLICATION_URL?>about/index/page/contact_us">Contact Us</a>

                                    </label>

                                </div>

                                

                                <div style="float:left;width:90px;"  align="center">

                                    <label class="footertext">

                                        <a href="<?=APPLICATION_URL?>about/index/page/shipping_rates">Shipping Rates</a>

                                    </label>

                                </div>

                                

                                 <div style="float:left;  width:90px;"  align="center">

                                    <label class="footertext">

                                        <a href="<?=APPLICATION_URL?>about/index/page/how_it_works">How it Works</a>

                                    </label>

                                </div>

                                

                              <div style="float:left; width:100px;"  align="center">

                                    <label class="footertext">

                                        <a href="<?=APPLICATION_URL?>about/index/page/terms_of_service">Terms of Service</a>

                                    </label>

                                </div>

                                

                               <div align="right" style="float:left; width:80px;"  align="center">

                                    <label class="footertext">

                                        <a href="<?=APPLICATION_URL?>about/index/page/privacy_policy">Privacy Policy</a>

                                    </label>

                                </div>

                                

                            </div>

                         </div>

                            

                           <div style="width:1000px; height:20px;">

                           	

                           </div>  

                            

                            

                            <div align="left" style="float:left; width:1000px;">

                            

                            	

                                <div style="float:left; width:30px; margin-left:2px; height:30px;">

                                    <a style="cursor:pointer;" href="http://www.google.com/+/learnmore/hangouts/?gpsrc=insebr&gclid=CLuK0dOF27UCFdFt6wodZXEAwQ"><img src="<?=IMAGES_URL?>google+.png" /></a>

                                </div>

                                

                                <div style="float:left; margin-left:3px; width:30px; height:30px;">

                                    <a href="http://www.linkedin.com/"><img src="<?=IMAGES_URL?>inimg.png" /></a>

                                </div>

                                

                               <div style="float:left; margin-left:3px; margin-top:-6px; width:30px; height:30px;">

                                    <a href="http://www.youtube.com/"><img src="<?=IMAGES_URL?>youtubeimg.png" /></a>

                                </div>

                                

                               <div style="float:left; margin-left:3px;  width:30px; height:30px;">

                                    <a style="cursor:pointer;" href="https://twitter.com/"><img src="<?=IMAGES_URL?>twitterimg.png" /></a>

                                </div>

                                

                               <div style="float:left; margin-left:3px;  width:30px; height:30px;">

                                    <a href="https://www.facebook.com/" style="cursor:pointer;"><img src="<?=IMAGES_URL?>fbimg.png" /></a>

                               </div>

                                

                            </div>

                            

                            

                          <div style="width:1000px; height:20px; float:left;">

                           </div>  

                            

                             

                            

                            <div align="left" style="margin-top:0px; margin-left:0px;">

                                <label style="font-family:Arial; color:#0dd25c; font-size:12px;">

                                    © TeeshirtSCRIPT.com

                                </label>

                                <label style="font-family:Arial; font-size:12px; color:#cccaca;"> 

                                    All rights reserved.

                                </label>

                            </div>

                      

                        

        </div>

</div>









<!--<div style="padding:0px;margin:0px;width:100%;">



<div style="border-top:#D9D9D9 solid 1px; width:100%; background-color:#FAFAFA;">

    	

        <div style="float:left; padding-top:20px; padding-left:190px" align="left">

       		<label style="font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; color:#5B5B5B; font-size:16px">

              Teespring allows you to crowdfund awesome custom apparel. <br />

            </label>

           

            <div style="float:left">

              <img src="<?=IMAGES_URL?>fblike.png" /> 

            </div>

            

            <div style="float:left; padding-top:10px; padding-left:10px"> 

            <label style="font-family:Arial, Helvetica, sans-serif; font-size:14px; color:#000;">4,866 people this.</label>

            </div>

            

        </div>

        

        <div style="float:left; padding-top:20px; padding-left:150px; padding-right:150px">

        	<label style="font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; color:#5B5B5B; font-size:16px">

        	  Connect

             </label>

             <div>

             	 <img src="<?=IMAGES_URL?>twitter.png" /> 

             </div>

        </div>

        

        <div style="float:left; padding-top:20px;">

           <label style="font-family:'Trebuchet MS', Arial, Helvetica, sans-serif; color:#5B5B5B; font-size:16px">

             Create

            </label>

            

            <div style="padding-top:5px">

            	<label style="font-family:'Times New Roman', Times, serif; color:#5B5B5B; font-size:16px; color:#06F">

                   Launch a Campaign

                </label>

            </div>

            

            <div style="padding-top:5px">

            	<label style="font-family:'Times New Roman', Times, serif; color:#5B5B5B; font-size:16px; color:#06F">

                   How it Works

                </label>

            </div>

            

        </div>

        

              <div style="width:1000px; padding-left:180px; padding-top:120px; padding-bottom:20px">

                 

               

                  <table cellpadding="0" cellspacing="0" border="0"> 

                    <tr>

                         <td style="padding:0px; font-size:14px; color:#999;">

                             © Teespring.com. All Rights Reserved.  

                          </td>

                          

                         <td style="padding-left:220px; padding-right:50px; font-size:14px; color:#999;"> 

                         	<a href="<?=APPLICATION_URL?>about/index/pageid/3" style="text-decoration:none; color:#999999"> FAQ </a>

                         </td>

                         

                         

                         

                         <td width="80px" style=" padding-right:50px; font-size:14px; color:#999;">

                         	<a href="<?=APPLICATION_URL?>about/index/pageid/2" style="text-decoration:none; color:#999999"> Contact Us</a>

                         </td>

                         

                        

                         

                         <td width="120px" style=" padding-right:50px; font-size:14px; color:#999;">

                         	<a href="<?=APPLICATION_URL?>about/index/pageid/7" style="text-decoration:none; color:#999999"> Terms of Service </a>

                         </td>

                         

                         

                         

                         <td width="120px" style=" padding-right:50px; font-size:14px; color:#999;">

                          <a href="<?=APPLICATION_URL?>about/index/pageid/19" style="text-decoration:none; color:#999999">	Privacy Policy</a>

                         </td>

                         

                    </tr>

               </table>   

                      

           </div>

        

    </div>

</div>-->





<script>

function fbshare()

{

	window.open ("http://www.facebook.com", "Facebook_Share","menubar=1,resizable=1,width=900,height=500");

}

function tweetshare()

{

	window.open ("http://twitter.com", "Twitter_Share","menubar=1,resizable=1,width=900,height=500");

}

function youtubeshare()

{

	window.open ("http://www.youtube.com", "Youtube_Share","menubar=1,resizable=1,width=900,height=500");

}

</script>



