
<script type="text/javascript" src="<?=APPLICATION_URL?>tinymce/jscripts/tiny_mce/tiny_mce.js"></script>



<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check"><?=$this->pageHeading?></span>
    </div>
    <div class="mws-panel-body">
        <form name="myform" id="mws-validate" action="<?php echo $this->url(array('controller'=>'testimonials', 'action'=>'savetestimonials'), 'default', true)?>" method="post" novalidate="novalidate" class="mws-form" enctype="multipart/form-data">
            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
            <div class="mws-form-inline">
                <div class="mws-form-row">
                    <label>Name :</label>
                    <div class="mws-form-item large">
                        <?=$this->myform->cat_name?><!--<input type="text" class="mws-textinput required" name="reqField">-->
                    </div>
                </div>
                <div class="mws-form-row">
                    <label>Site Name :</label>
                    <div class="mws-form-item large">
                        <?=$this->myform->cat_sitename?><!--<input type="text" class="mws-textinput required" name="reqField">-->
                    </div>
                </div>
                <div class="mws-form-row">
                    <label>Image :</label>
                    <div class="mws-form-item large">
                        <?=$this->myform->image?><!--<input type="text" class="mws-textinput required" name="reqField">-->
                    </div>
                </div>
                <div class="mws-form-row">
                <label>Content</label>
                <div class="mws-form-item">
                    <?=$this->myform->cat_description?>
                </div>
            </div>
            <div class="mws-button-row">
                <input type="submit" value="Submit" class="mws-button red" />
            </div>
        </form>
    </div>    	
</div> 