<form method="post" name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'pages', 'action'=>'index'), 'default', true)?>" >
<div class="mws-panel grid_8">
                	<div class="mws-panel-header">
                    	<span class="mws-i-24 i-table-1"><?=$this->pageHeading?></span>
                    </div>
                    <div class="mws-panel-body">
                        <div class="mws-panel-toolbar top clearfix ">
                        <ul>
                       <li>
                       

                        <!--<a href="<?php echo $this->url(array('controller'=>'pages', 'action'=>'add'), 'default', true)?>" class="mws-ic-16 ic-accept" href="<?=APPLICATION_URL_ADMIN?>users/adduser/uType/<?=$this->uType?>" title="Add">Add</a></li>-->
                       <!-- <li><a class="mws-ic-16 ic-cross" href="javascript:void(0)" title="Delete"  onclick="deleteRecord();">Delete</a></li>-->
                        </ul>
                        </div>
                        <table class="mws-datatable-fn mws-table">
                            <thead>
                                <tr>
                                    <th width="5%">S.No.</th>
                                    <th width="45%">Page Title</th>
                                    
                                    <th width="5%" class="">Edit</th>
                                    <th width="3%"></th>
                                </tr>
                            </thead>
                            <tbody>
                            	<?php
								
								
					for($i=0;$i<count($this->sql);$i++)
					{
					?>
									
									<tr class="gradeX">
                                        <td><?=$i+1;?></td>
                                        <td><?=$this->sql[$i]['page_title']?></td>
                                       
                                        
                                        <td class="center">
                                         <a href="<?=APPLICATION_URL_ADMIN?>pages/edit/pageId/<?=$this->sql[$i]['page_id']?>">
            <img src="<?=APPLICATION_URL_ADMIN;?>css/icons/16/edit.png" border='0' />
            </a>
           
                                           
                                        </td> 
                                        <td>
             <input type="checkbox" name="checkbox[]" id="checkbox[]" value="<?=$this->sql[$i]['page_id']?>"  onClick="return check1();"/>
                 
                                        </td>
	                                </tr>
									<?php
								}
								?>
                                
                                 
                            </tbody>
                        </table>
                    </div>
                </div>
                
                <!-- Panels End -->
            </div>
            </form>
            
<script type="text/javascript">

function deleteRecord()
{ 

var pIds='';
var userrows=new Array();
var cboxes=document.getElementsByName("checkbox[]");

for(i=0;i<cboxes.length;i++){ 
if(cboxes[i].checked==true)
{
	pIds+=cboxes[i].value+','; 
	userrows[i]=cboxes[i].value;
	
		
	}
}
if(pIds==""){alert("Please select atleast one record.");return;}


if(confirm("Are you sure to delete these records?"))
{



$.ajax({ 
    type: "POST", 
    url: "<?=APPLICATION_URL_ADMIN."pages/deletepages/pID/"?>"+pIds,
    data: ({userId:pIds}),
    cache: false, 

    success: function(data){
   window.location ="<?=APPLICATION_URL_ADMIN?>pages/index";		
	   }
   }); 




}

}



</script>

            
            
            
            