<!--<script src="<?=APPLICATION_URL?>jscolor/jscolor.js" type="text/javascript"></script>
--><?php
	global $mySession;
	$db=new Db();
	
?>
<div class="mws-panel grid_8">
     <div class="mws-panel-header">
             <span class="mws-i-24 i-check"><?=$this->pageHeading?></span>
      </div>
            <div class="mws-panel-body">
					<form name="myform" id="myform" class="mws-form" action="<?php echo $this->url(array('controller'=>'tshirt', 'action'=>'savenewicon'), 'default', true)?>" method="post" enctype="multipart/form-data">
                        	 <table align="center" cellpadding="5" cellspacing="5" border="0" style="margin-left:30px;">
								<div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
                                <div class="mws-form-inline">
                                <div class="mws-form-row">
                                	<label>Image :  <span class="error2">*</span></label>
                                	<div class="mws-form-item large" style="width:300px;">
                                    	<?=$this->myform->image?> 
                                    
                                    </div>
                                </div>
                                    <div class="mws-form-row">
                                	<label>Title : <span class="error2">*</span> </label>
                                	<div class="mws-form-item large">
                                    	<?=$this->myform->title?>
                                    </div>
                                </div> 
                              <div class="mws-form-row">
                                        <label>Color Code : <span class="error2">*</span> </label>
                                        <div class="mws-form-item large">
                                        <?=$this->myform->colorcode?>
                                        <br />
                                        Enter Color Code of  Icon You are uploading.
                                        </div>
                                        </div>
                                	  <div class="mws-button-row">
                                 
                            
                              
                                <input type="submit" name="Add" id="Add Icon" value="Add" class="mws-button red">
                      
                            </div>
                          </div>
                    </table>
                        </form>
      </div>    	
</div>

<script>
function checknummspK(e)
{ 

	evt=e || window.event;
	var keypressed=evt.which || evt.keyCode;
		if(keypressed=="35")
	{ 
 		return false;
	}
 
 	
	
}
</script>
                
                    	
             