<form method="post" name="myform" id="myform" action="<?php echo $this->url(array('controller'=>'tshirt', 'action'=>'discount'), 'default', true)?>" >
<div class="mws-panel grid_8">
                	<div class="mws-panel-header">
                    	<span class="mws-i-24 i-table-1"><?=$this->pageHeading?></span>
                    </div>
                    <div class="mws-panel-body">
                        <div class="mws-panel-toolbar top clearfix ">
                        <ul>
                       <li>
                       
                        </ul>
                        </div>
                        <table class="mws-datatable-fn mws-table">
                            <thead>
                                <tr>
                                    <th width="5%">S.No.</th>
                                    <th width="45%">No. Of TShirt</th>
                                     <th width="45%">Discount (%)</th>
                                    <th width="5%" class="">Edit</th>
                                  
                                </tr>
                            </thead>
                            <tbody>
                            	<?php
								
								
					for($i=0;$i<count($this->sql);$i++)
					{
					?>
									
									<tr class="gradeX">
                                        <td><?=$i+1;?></td>
                                        <td><?=$this->sql[$i]['no_of_tee']?></td>
                                       
                                         <td><?=$this->sql[$i]['discount_per']?></td>
                                         
                                        <td class="center">
                                         <a href="<?=APPLICATION_URL_ADMIN?>tshirt/editdiscount/sno/<?=$this->sql[$i]['sno']?>">
            <img src="<?=APPLICATION_URL_ADMIN;?>css/icons/16/edit.png" border='0' />
            </a>
           
                                           
                                        </td> 
                                      
	                                </tr>
									<?php
								}
								?>
                                
                                 
                            </tbody>
                        </table>
                    </div>
                </div>
                
                <!-- Panels End -->
            </div>
            </form>
            
<!--<script type="text/javascript">

function deleteRecord()
{ 

var pIds='';
var userrows=new Array();
var cboxes=document.getElementsByName("checkbox[]");

for(i=0;i<cboxes.length;i++){ 
if(cboxes[i].checked==true)
{
	pIds+=cboxes[i].value+','; 
	userrows[i]=cboxes[i].value;
	
		
	}
}
if(pIds==""){alert("Please select atleast one record.");return;}


if(confirm("Are you sure to delete these records?"))
{



$.ajax({ 
    type: "POST", 
    url: "<?=APPLICATION_URL_ADMIN."pages/deletepages/pID/"?>"+pIds,
    data: ({userId:pIds}),
    cache: false, 

    success: function(data){
   window.location ="<?=APPLICATION_URL_ADMIN?>pages/index";		
	   }
   }); 




}

}



</script>-->

            
            
            
            