
<script type="text/javascript" src="<?=APPLICATION_URL?>tinymce/jscripts/tiny_mce/tiny_mce.js"></script>

<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-check"><?=$this->pageHeading?></span>
    </div>
    <div class="mws-panel-body">
        <form name="myform" id="mws-validate" action="<?php echo $this->url(array('controller'=>'tshirt', 'action'=>'updatesize','sno'=>$this->sno), 'default', true)?>" method="post" novalidate class="mws-form">
            <div style="display:none;" class="mws-form-message error" id="mws-validate-error"></div>
            <div class="mws-form-inline">
                <div class="mws-form-row">
                    <label>Size:</label>
                    <div class="mws-form-item large">
                        <?=$this->myform->sizes?>
                    </div>
                </div>
                <div class="mws-form-row">
                <label>In Inches</label>
                <div class="mws-form-item">
                    <?=$this->myform->ininches?>
                </div>
            </div>
            <div class="mws-button-row">
                <input type="submit" value="Submit" class="mws-button red" />
            </div>
        </form>
    </div>    	
</div> 