<div class="work_section_two  mainprofile" id="forgotpass">
	<form name="myform" id="myform" method="post" action="<?=$this->url(array('controller'=>'login', 'action'=>'getpassword'), 'default', true)?>" onsubmit="return validformdata();">
	<div class="top10pxmargin " style="margin-top:0px;">
		<label >Enter the email address you used to create your account and we'll email you instructions to reset your password.</label>
	</div>

	<div class="top10pxmargin ">
		<label class="myaccsubtitles">Email Address</label>
	</div>
	
	<div class="top5pxmargin">
		<?=$this->myform->emailid?>
	</div>
	
	<div class="top10pxmargin " >
		<input type="submit" name="loginbtn" id="loginbtn" style="width:260px" value="Recover Your Password" class="accbutton">
	</div>

	</form>
</div>

       