<link rel="stylesheet" type="text/css" href="<?=CSS_URL?>demo.css" />
        <link rel="stylesheet" type="text/css" href="<?=CSS_URL?>style1.css" />
        <link href='http://fonts.googleapis.com/css?family=Terminal+Dosis' rel='stylesheet' type='text/css' />


                <ul class="ca-menu">
                    <li>
                      <a href="<?=APPLICATION_URL?>about/index/pageid/22">

                            <div class="ca-content">
                                <h2 class="ca-main"> How it works</h2>
                             <!--   <h3 class="ca-sub">Personalized to your needs</h3>-->
                            </div>
                        </a>
                    </li>
                      <li>
                        <a href="<?=APPLICATION_URL?>about/index/pageid/3">

                            <div class="ca-content">
                                <h2 class="ca-main">FAQ</h2>
                             <!--   <h3 class="ca-sub">Understanding visually</h3>-->
                            </div>
                        </a>
                    </li>

					<li>
                        <a href="<?=APPLICATION_URL?>about/index/pageid/21">

                            <div class="ca-content">
                                <h2 class="ca-main"> Shipping Rates </h2>
                             <!--   <h3 class="ca-sub">Understanding visually</h3>-->
                            </div>
                        </a>
                    </li>


                    <li>
                        <a href="<?=APPLICATION_URL?>about/index/pageid/19">

                            <div class="ca-content">
                                <h2 class="ca-main">Privacy policy </h2>
                             <!--   <h3 class="ca-sub">Understanding visually</h3>-->
                            </div>
                        </a>
                    </li>

                    <li>
                        <a href="<?=APPLICATION_URL?>about/index/pageid/7">

                            <div class="ca-content">
                                <h2 class="ca-main"> Terms of Sevice </h2>
                             <!--   <h3 class="ca-sub">Understanding visually</h3>-->
                            </div>
                        </a>
                    </li>

                     <li>
                        <a href="<?=APPLICATION_URL?>about/index/pageid/2">

                            <div class="ca-content">
                                <h2 class="ca-main"> Contact Support</h2>
                             <!--   <h3 class="ca-sub">Understanding visually</h3>-->
                            </div>
                        </a>
                    </li>
                </ul>
<!--
 <div align="center" class="aboutmenufont">
                <ul class="navig navig-list" style="list-style:none; text-align:left; padding-left:5px">
                    <li class="listheading1">
                       ABOUT TEESPRING
                    </li>
                    <li>
                       <a href=""> How it works </a>
                    </li>
                    <li>
                       <a href="<?=APPLICATION_URL?>about/index/pageid/3" style="text-decoration:none; color:#1D98E2"> FAQ </a>
                    </li>

                    <li>
                        <a href=""> Examples </a>
                    </li>
                    <li>
                       <a href="<?=APPLICATION_URL?>about/index/pageid/21" style="text-decoration:none; color:#1D98E2"> Shipping Rates </a>
                    </li>
                  <li class="listheading1" style="padding-top:10px">
                       HOW TO SELL
                  </li>
                   <li>
                        <a href=""> Teespring School </a>
                   </li>
                   <li class="listheading1" style="padding-top:10px">
                        OUR POLICIES
                  </li>
                    <li>
                       <a href="<?=APPLICATION_URL?>about/index/pageid/19" style="text-decoration:none; color:#1D98E2"> Privacy policy </a>
                    </li>
                    <li>
                       <a href="<?=APPLICATION_URL?>about/index/pageid/7" style="text-decoration:none; color:#1D98E2"> Terms of Sevice </a>
                    </li>
                </ul>
            <hr style="width:180px; color:#FFF;" align="center"/>

                 <ul class="navig navig-list" style="list-style:none; padding-left:5px; text-align:left">

                   <li>
                      <a href="<?=APPLICATION_URL?>about/index/pageid/2" style="text-decoration:none; color:#1D98E2"> Contact Support </a>
                    </li>
                 </ul>

        </div>-->