<?php

global $mySession;

$db=new Db();

?>


<!--------------Footer--------------->

<!------/footer----->
<div class="col-md-12 footer">
    <ul class="nav links navbar-nav">
        <li> <a href="<?php echo APPLICATION_URL;?>about/index/page/faq">FAQ</a></li>
        <li><a href="<?php echo APPLICATION_URL;?>about/index/page/contact_us">CONTACT US </a></li>
        <li><a href="<?php echo APPLICATION_URL;?>about/index/page/shipping_rates">SHIPPING RATES </a></li>
        <li><a href="<?php echo APPLICATION_URL;?>about/index/page/how_it_works">HOW IT WORKS </a></li>
        <li><a href="<?php echo APPLICATION_URL;?>about/index/page/terms_of_service">TERMS OF SERVICE </a></li>
        <li><a href="<?php echo APPLICATION_URL;?>about/index/page/privacy_policy">PRIVACE POLICE </a></li>
    </ul>

</div>


<div class="col-md-12 footer2">
    <div class="icons">
        <a href="http://www.google.com/+/learnmore/hangouts/?gpsrc=insebr&gclid=CLuK0dOF27UCFdFt6wodZXEAwQ"><i class="fa fa-google-plus" style="color:#fff;"></i></a>
        <a href="https://www.facebook.com/TMerchTees" target="_blank"><i class="fa fa-facebook-square" style="color:#fff;"></i></a>
        <a href="https://twitter.com/"><i class="fa fa-twitter" style="color:#fff;"></i><a/>
        <a href="http://www.youtube.com/"><i class="fa fa-youtube" style="color:#fff;"></i></a>
    </div>

</div>
<!------/end-footer---------->

<?php

/*
 *

<footer>
<div>
    <p><a  href="<?php echo APPLICATION_URL;?>about/index/page/faq">FAQ</a>  |  <a href="<?php echo APPLICATION_URL;?>about/index/page/contact_us">Contact Us</a>  |  <a href="<?php echo APPLICATION_URL;?>about/index/page/shipping_rates">Shipping Rates</a>  |  <a href="<?php echo APPLICATION_URL;?>about/index/page/how_it_works">How it Works</a>  |  <a href="<?php echo APPLICATION_URL;?>about/index/page/terms_of_service">Terms of Service</a>  |  <a href="<?php echo APPLICATION_URL;?>about/index/page/privacy_policy">Privacy Policy</a></p>
<!--    <div class="col-md-12 footer">-->

<!--        <ul class="nav links navbar-nav">-->
<!--            <li><a  href="--><?php //echo APPLICATION_URL;?><!--about/index/page/faq" class="active2">FAQ | </a></li>-->
<!--            <li><a href="--><?php //echo APPLICATION_URL;?><!--about/index/page/contact_us">  CONTACT US </a></li>-->
<!--            <li><a href="--><?php //echo APPLICATION_URL;?><!--about/index/page/shipping_rates">SHIPPING RATES </a></li>-->
<!--            <li><a href="--><?php //echo APPLICATION_URL;?><!--about/index/page/how_it_works">NOW IT WORKS </a></li>-->
<!--            <li><a href="--><?php //echo APPLICATION_URL;?><!--about/index/page/terms_of_service">TERMS OF SERVICE </a></li>-->
<!--            <li><a href="--><?php //echo APPLICATION_URL;?><!--about/index/page/privacy_policy">PRIVACE POLICE </a></li>-->

<!--        </ul>-->
<!--    </div>-->

    <div>
        <div class="col-md-12 footer2">
            <div class="icons" >
                <a href="http://www.google.com/+/learnmore/hangouts/?gpsrc=insebr&gclid=CLuK0dOF27UCFdFt6wodZXEAwQ"><i class="fa fa-google-plus" style="color:#fff;"></i></a>
                <a href="https://www.facebook.com/"><i class="fa fa-facebook-square" style="color:#fff;"></i></a>
                <a href="https://twitter.com/"><i class="fa fa-twitter" style="color:#fff;"></i></a>
                <a href="http://www.youtube.com/"><i class="fa fa-youtube" style="color:#fff;"></i></a>
            </div>
        </div>
    </div>
</div>


<!--    -->
<!--	<div class="zerogrid">-->
<!---->
<!--		<div class="footer_left">-->
<!---->
<!--			<p>TeeshirtSCRIPT allows you to crowdfund awesome custom apparel.</p>-->
<!---->

<!---->
<!--		</div>-->
<!---->
<!--		<div class="footer_right">-->
<!---->
<!--			<div class="footer_logo"><a href="--><?php //echo APPLICATION_URL;?><!--"><img src="--><?php //echo IMAGES_URL;?><!--logo_footer.png" /></a></div>-->
<!---->
<!--			<div class="footer_social">-->
<!---->
<!--			<a href="http://www.google.com/+/learnmore/hangouts/?gpsrc=insebr&gclid=CLuK0dOF27UCFdFt6wodZXEAwQ"><img src="--><?php //echo IMAGES_URL;?><!--gp_ic.png"/></a>-->
<!---->
<!--			<a href="http://www.linkedin.com/"><img src="--><?php //echo IMAGES_URL;?><!--in_ic.png"/></a>-->
<!---->
<!--			<a href="http://www.youtube.com/"><img src="--><?php //echo IMAGES_URL;?><!--tw_ic.png"/></a>-->
<!---->
<!--			<a href="https://twitter.com/"><img src="--><?php //echo IMAGES_URL;?><!--fb_ic.png"/></a>-->
<!---->
<!--			<a href="https://www.facebook.com/"><img src="--><?php //echo IMAGES_URL;?><!--u_ic.png"/></a>-->
<!---->
<!--			</div>-->
<!---->
<!--		</div>-->
<!---->
<!--	</div>-->

</footer>

<script>

function fbshare()

{

	window.open ("http://www.facebook.com", "Facebook_Share","menubar=1,resizable=1,width=900,height=500");

}

function tweetshare()

{

	window.open ("http://twitter.com", "Twitter_Share","menubar=1,resizable=1,width=900,height=500");

}

function youtubeshare()

{

	window.open ("http://www.youtube.com", "Youtube_Share","menubar=1,resizable=1,width=900,height=500");

}

</script>

 */

?>


