<?php
global $mySession;
$db=new Db();
$myControllerName=Zend_Controller_Front::getInstance()->getRequest()->getControllerName();	
$myActionName=Zend_Controller_Front::getInstance()->getRequest()->getActionName();


?>
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title><?php echo SITE_NAME; ?> <?php if($this->pageTitle!="" ) { echo " - ".$this->pageTitle; } ?></title>
	<meta name="description" content="<?php echo SITE_NAME; ?> <?php if($this->pageTitle!="" ) { echo " - ".$this->pageTitle; } ?>">
	<meta name="author" content="<?php echo SITE_NAME; ?>">
	
    <!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- CSS
  ================================================== -->
	<link rel="stylesheet" href="<?php echo CSS_URL;?>zerogrid.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>style.css">
    <link rel="stylesheet" href="<?php echo CSS_URL;?>responsive.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>240.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>320.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>480.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>768.css">

	
	<link rel="stylesheet" type="text/css" href="<?php echo APPLICATION_URL;?>creator/css/jquery.fancyProductDesigner-fonts.css" />
	
	<link rel="stylesheet" href="<?php echo CSS_URL;?>jquery.countdown.css" type="text/css">
	
	<link rel="stylesheet" href="<?=APPLICATION_URL?>fancybox/source/jquery.fancybox.css?v=2.1.0" media="screen"  />
	
	<link rel="stylesheet" type="text/css" href="<?=APPLICATION_URL?>creator/css/jquery.fancyProductDesigner-fonts.css" />

	
	<!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
		<script src="<?php echo JS_URL;?>html5.js"></script>
		<script src="<?php echo JS_URL;?>css3-mediaqueries.js"></script>
	<![endif]-->
	
	<script src="<?php echo JS_URL;?>jquery.min.js" type="text/javascript"></script>
    <!--<script type="text/javascript" src="<?php echo JS_URL_ADMIN;?>jquery-ui.js"></script>-->
	<script src="<?php echo JS_URL;?>general.js" type="text/javascript" ></script>

	<script src="<?php echo JS_URL;?>jquery.countdown.js" type="text/javascript" ></script>
	<script type="text/javascript" src="<?php echo APPLICATION_URL;?>creator/html2canvas.js"></script>

	<script type="text/javascript" src="<?=APPLICATION_URL?>fancybox/source/jquery.fancybox.js?v=2.1.0"></script>
	
	<link href="<?=JS_URL?>scroller/jquery.mCustomScrollbar.css" rel="stylesheet" />
	<script src="<?=JS_URL?>scroller/jquery.mCustomScrollbar.concat.min.js"></script>
	<script type="text/javascript" src="<?=JS_URL?>jquery.bxslider.js"></script>
	<link href="<?=CSS_URL?>jquery.bxslider.css" rel="stylesheet" />

	

			
    <script type="text/javascript" >
    $("#myInformationDiv").ready(function () { 

      $("#myInformationDiv2").show(1000);

    });

	setTimeout(function() {

	$("#myInformationDiv2").hide("fast", function () {
		// use callee so don't have to name the function
		$(this).prev().hide("fast", arguments.callee); 
	});

	}, 7000);
	
	function showhide_commentbox(Stat,Id,Id1) 
	{
		if(Stat!="")
		{
			$('#answer'+Id+Id1).slideToggle("slow");
		}
	}
	
	$(document).ready(function() {
		if(document.getElementById('frontDataValK').value=='front')
		{
			$('#onlyFrontDataK').css("display","block");
		}
		else
		{
			$('#bothdatakmanika').css("display","block");
		}
	});

	function showtee()
	{
		$('#Tees1').css("display","none");
		$('#Tees0').css("display","block");
	}

	function showtee1()
	{
		$('#Tees0').css("display","none");
		$('#Tees1').css("display","block");
	}
	</script>
	<script type="text/javascript">
	$(document).ready(function() {
		$('#edit1').fancybox();
		$('#edit2').fancybox();
	});
	</script>


	<script>

	(function($){

	$(window).load(function(){

	$("#content_1").mCustomScrollbar({

	scrollButtons:{

	enable:true

	}

	});

	$("#content_2").mCustomScrollbar({

	scrollButtons:{

	enable:true

	}

	});

	


	function findPos(obj){

	var curleft=curtop=0;

	if (obj.offsetParent){

	curleft=obj.offsetLeft

	curtop=obj.offsetTop

	while(obj=obj.offsetParent){

	curleft+=obj.offsetLeft

	curtop+=obj.offsetTop

	}

	}

	return [curtop,curleft];

	}

	});

	})(jQuery);

	</script>



	<script>

	function follow()

	{//alert(searchStr);

	var id='<?=$this->id?>';

	$.ajax({ url: "<?=APPLICATION_URL."user/folowuser"?>",	

	type: "POST",	

	data: ({id:id}),	

	success: function(data)

	{

	window.location.href=window.location.href;



	}});

	}

	function unfollow()

	{//alert(searchStr);

	var id='<?=$this->id?>';

	$.ajax({ url: "<?=APPLICATION_URL."user/unfollow"?>",	

	type: "POST",	

	data: ({id:id}),	

	success: function(data)

	{

	window.location.href=window.location.href;



	}});

	}



	jQuery(document).ready(function() {

	if(document.getElementById('frontDataValK').value=='front')

	{

	$('#onlyFrontDataK').css("display","block");



	}

	else

	{

	$('#bothdatakmanika').css("display","block");

	}



	});


	</script>
	<link href='<?php echo IMAGES_URL;?>favicon.ico' rel='icon' type='image/x-icon'/>
	<style>
	.fpd-recreation {
		background: none repeat scroll 0 0 white;
		margin-left: 91px;
		position: relative;
		width: 451px;
	}  	

	.fpd-recreation div {
		position: relative;
		height: 570px;
        /*margin-left: -42px;*/
	}

	.fpd-recreation img, .fpd-recreation canvas, .fpd-recreation span {
		position: absolute;
	}

	#Tees0
	{
		display:block;
	}

	#Tees1
	{
		display:none;
	}

	.frontBack {
		color: #0099CC;
		font-family: Calibri;
		font-size: 18px;
		height: 20px;
		margin-top: 31px;
		padding-left: 50px;
		position: absolute;
		width: 579px;
	}

	#onlyFrontDataK ,#bothdatakmanika
	{
		display:none;
	}

	.addanother

	{

		font-size:16px;

		height:28px;

		width:103px;

		border:#000 solid 1px;

		border-radius:2px;

		cursor:pointer;

		margin-top:5px;

	}

	#paypalchk-1

	{

		margin:10px;

	}

	#paypalchk-2

	{

		margin:10px;

	}
	.info_text { clear:both; padding:0 0 40px 40px;}
	
	#Tees0

	{

		height:570px;

	}

	#Tees1

	{

		height:570px;

	}

	.content1 {

		border-radius: 3px 3px 3px 3px;

		height: 230px;

		overflow: hidden;

		width: 300px;

		float:left;

		border-right:2px solid #40BCD8;

	}

	.content2 {

		border-radius: 3px 3px 3px 3px;

		height: 230px;

		overflow: hidden;

		width: 300px;

		float:left;

		margin-left:5px;

	}

	.followuser{

		float: left;

		font-size: 11px;

		height: 10px;

		margin-left: 92px;

		margin-top: -30px;

	}
	
	

	.bio

	{ float: left;

		height: 100px;

		padding-left: 6px;

		text-align: left;

		width: 400px;

	}

	.loginlayout

	{

		width:1000px;

		height:auto;

	}

	</style>

</head>   
<body id="page1">
	<input type="hidden" id="frontDataValK" value="" />
	<?php if( $mySession->errorMsg!=""){ ?>

	<div id="myInformationDiv" style="position:absolute; width:100%; top:133px; ">

		<div id="myInformationDiv2" align="center" style="position:absolute; width:100%; display:block; color:#000;background-color:#319ebc; height:36px; font-family:Verdana, Geneva, sans-serif;"> 
		<?=$mySession->errorMsg?>
		</div>
	</div>
	<?php unset($mySession->errorMsg); } ?>

	<?php include ("header_1.phtml"); ?>
	
	
	<!--------------profile--------------->
<div class="banner">
  <div class="zerogrid">
    <div style="margin-bottom:0px;" class="row block">
      <div id="align_both">
        <div class="top_info">
          <div class="info_left" id="in_left">
				<?php if($this->dataQry['profile_image']!="" && file_exists(SITE_ROOT.'images/profileimages/'.$this->dataQry['profile_image'])) { ?>
					<img src="<?=APPLICATION_URL?>images/profileimages/<?=$this->dataQry['profile_image']?>" height="67" width="67" border="0" style="border: solid 1px #ADADAD;" />
				<?php  }  else   {   ?>
					<img src="<?=APPLICATION_URL?>images/profileimages/follwing_ic2.png" height="67" width="67" border="0"  style="border: solid 1px #ADADAD;" />
				<?php  }   ?>
				<?=$this->dataQry['public_name']?>'s  profile
			</div>
			<div class="info_right" id="use_in_right">
			<?php if($mySession->TeeLoggedID==''){ ?>
			  <a id="edit1"  href="<?=APPLICATION_URL?>login/follow">
				<div class="follow btn">
				  <div style="margin-left:25px;">follow</div>
				</div>
				</a>
				<a id="edit2"  href="<?=APPLICATION_URL?>login/hire">
				<div class="hire btn">
				  <div style="margin-left:20px;">hire</div>
				</div>
				</a>
			<?php } else if($this->id!=$mySession->TeeLoggedID){?>
			<?php $chk=$db->runquery("select * from ".FOLLOW." where follower_id='".$mySession->TeeLoggedID."' and following_id='".$this->id."' ");

		   if(count($chk)==1){ ?>
			<a onclick="unfollow();" href="javascript:void(0);">
            <div class="follow btn">
              <div style="margin-left:25px;">unfollow</div>
            </div>
            </a>
			<?php } else { ?>
			<a onclick="follow();"  href="javascript:void(0);">
            <div class="follow btn">
              <div style="margin-left:25px;">follow</div>
            </div>
            </a>
			<?php } ?>
			<a href="<?=APPLICATION_URL?>user/hireuser/user_id/<?=$this->id?>">
            <div class="hire btn">
              <div style="margin-left:20px;">hire</div>
            </div>
            </a>
			<?php } ?>
			<div id="inline1" style="display:none">
				Please login to follow this user or to hire this user
			</div>
			</div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--------------Content--------------->
<section id="content">
  <div class="zerogrid">
    <div class="row block">
      <div class="main-content">
        <div class="followers_user">
			<div class="followers_user_left">Following</br>
				<span id="content_2">
					<?php foreach($this->follower as $follower)  { ?>
						<a href="<?=APPLICATION_URL?>user/view/user_id/<?=$follower['user_id']?>" >
						<?php  if($follower['profile_image']!="" && file_exists(SITE_ROOT.'images/profileimages/'.$follower['profile_image']))  { ?>
						<img src="<?=APPLICATION_URL?>images/profileimages/<?=$follower['profile_image']?>" height="45" width="45" border="0"/>
						<?php }  else   { ?>
						<img src="<?=APPLICATION_URL?>images/profileimages/follwing_ic2.png" height="45" width="45" border="0"  />
						<?php   }    ?>
						</a>      
					<?php } ?>
				</span>
			</div>
			<div class="followers_user_right">Followers</br>
				<span id="content_1" >
					<?php foreach($this->follow as $follow) { ?>
						<a href="<?=APPLICATION_URL?>user/view/user_id/<?=$follow['user_id']?>" >
							<?php  if($follow['profile_image']!="" && file_exists(SITE_ROOT.'images/profileimages/'.$follow['profile_image']))  {  ?>
								<img src="<?=APPLICATION_URL?>images/profileimages/<?=$follow['profile_image']?>" height="45" width="45" border="0" />
							<?php  }  else   { ?>
								<img src="<?=APPLICATION_URL?>images/profileimages/follwing_ic2.png" height="45" width="45" border="0" />
							<?php      }   ?>
						</a>
					<?php } ?>
				</span>
			</div>
        </div>
		<?php echo $this->layout()->content; ?>        
      </div>
    </div>
    <div class="bot_margin">
      <div class="bot_signup"><a id="bottm_sign" style="display:inline-block; padding-right:34px; padding-top:12px;" href="#">Create your own tee!</a> <a href="#"><span class="btn">Get started</span></a></div>
    </div>
  </div>
</section>
<!--------------Footer--------------->

	<?php include ("footer_1.phtml"); ?>
	</body>
</html> 
  

