<div class="launchBG" style="width:100%;">

    <div style="width:1000px; height:35px;">

        <div style="float:left; width:700px; height:35px;">

            <div class="content" style="float:left; width:160px; height:35px;">
               <a href="<?=APPLICATION_URL?>launchcampaign/index"> 1. Create Your Tee </a>
               <!--<a href="javascript:ajaxpage('launchcampaign/index');"> 1. Create Your Tee</a>-->
            </div>

            <div class="point" style="width:13px; height:35px; float:left;">
            </div>

            <div class="content" style="float:left; height:35px; width:150px;">
               <a href="<?=APPLICATION_URL?>launchcampaign/setgoal"> 2. Set a Goal </a>
              <!--   <a href="javascript:ajaxpage('launchcampaign/setgoal');"> 2. Set a Goal </a>-->
            </div>

            <div class="point" style="width:13px; height:35px; float:left;">
            </div>

            <div class="content" style="float:left; height:35px; width:180px;">
               <a href="<?=APPLICATION_URL?>launchcampaign/adddescription"> 3. Add a Description </a>
            </div>

             <div class="point" style="width:13px; height:35px; float:left;">
             </div>
        </div>


        <div align="right" style="width:270px; height:35px; float:left;">

            <div class="content" style="float:left; width:90px; height:35px;">
                 <a href="<?=APPLICATION_URL?>">
                 <div style="float:left">
                    <img src="<?=IMAGES_URL?>savefolder.png" height="25" width="20"/>
                  </div>
                  <div>
                   Save
                  </div> </a>
            </div>

           <!-- <div style="width:20px; height:35px; float:left">
            </div>
            -->
            <div class="content" style="float:left; width:90px; height:35px;">
                   <a href="<?=APPLICATION_URL?>">
                 <div style="float:left; margin-top:5px;">
                    <img src="<?=IMAGES_URL?>Mail.png" height="15" width="20"/>
                 </div>
                 <div>
                   Share
                 </div> </a>
            </div>
            <div class="content" style="float:left; width:90px; height:35px;">
                   <a href="<?=APPLICATION_URL?>">
                 <div style="float:left">
                    <img src="<?=IMAGES_URL?>prevwicon.png" height="20" width="20"/>
                 </div>
                 <div>
                 Preview
                 </div> </a>
            </div>
        </div>
    </div>
</div>

