<div>
<div align="center" style="width:100%; background-image:url(<?=IMAGES_URL?>mainbackg.png); background-repeat:repeat;">
<div align="center" style="height:320px; width:220px; margin-bottom:20px; background-color:#EBEBEB; border-radius:5px; border:#C1C1C1 solid 2px; float:left">


                <ul class="nav nav-list" style="list-style:none; text-align:left; padding-left:5px">
                    <li class="listheading">
                        CAMPAIGNS
                    </li>
                    <li>
                       <a href="<?=APPLICATION_URL?>myaccount/activecampaign"> Active </a>
                    </li>
                    <li>
                        <a href=""> Ended </a>
                    </li>

                    <li>
                        <a href=""> Drafts </a>
                    </li>

                    <li class="listheading" style="padding-top:10px">
                        ACCOUNT
                    </li>
                    <li>
                         <a href="<?=APPLICATION_URL?>myaccount/profile"> Profile </a>
                    </li>
                    <li>
                        <a href=""> Get Paid </a>
                    </li>
                    <li>
                       <a href="<?=APPLICATION_URL?>myaccount/changepassword"> Change Password </a>
                    </li>
                    <li>
                        <a href=""> Refer a Friend </a>
                    </li>
                </ul>


            <hr style="width:180px; color:#FFF;" align="center"/>

                 <ul class="nav nav-list" style="list-style:none; padding-left:5px; text-align:left">
                  <!--  <li class="list">-->
                   <li>
                        <a href="">  Contact Support </a>
                    </li>
                 </ul>

        </div>

</div>