<?php
global $mySession;
$db=new Db();
$myControllerName=Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$myActionName=Zend_Controller_Front::getInstance()->getRequest()->getActionName();


?>
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

    <!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title><?php echo SITE_NAME; ?> <?php if($this->pageTitle!="" ) { echo " - ".$this->pageTitle; } ?></title>
	<meta name="description" content="<?php echo SITE_NAME; ?> <?php if($this->pageTitle!="" ) { echo " - ".$this->pageTitle; } ?>">
	<meta name="author" content="<?php echo SITE_NAME; ?>">

    <!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
  ================================================== -->
	<link rel="stylesheet" href="<?php echo CSS_URL;?>zerogrid.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>style.css">
    <link rel="stylesheet" href="<?php echo CSS_URL;?>responsive.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>240.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>320.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>480.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>768.css">
	<link rel="stylesheet" href="<?php echo CSS_URL;?>bootstrap.css">


<!--    <link rel="stylesheet" type="text/css" href="--><?//=APPLICATION_URL?><!--bootstrap/css/bootstrap.css" />-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="<?=APPLICATION_URL?>js/bootstrap.min.js" type="text/javascript"></script>

	<link rel="stylesheet" type="text/css" href="<?php echo APPLICATION_URL;?>creator/css/jquery.fancyProductDesigner-fonts.css" />

	<link rel="stylesheet" href="<?php echo CSS_URL;?>jquery.countdown.css" type="text/css">

	<!--[if lt IE 8]>
       <div style=' clear: both; text-align:center; position: relative;'>
         <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
           <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
      </div>
    <![endif]-->
    <!--[if lt IE 9]>
		<script src="<?php echo JS_URL;?>html5.js"></script>
		<script src="<?php echo JS_URL;?>css3-mediaqueries.js"></script>






	<![endif]-->

	<script src="<?php echo JS_URL;?>jquery.min.js" type="text/javascript"></script>

    <!--<script type="text/javascript" src="<?php echo JS_URL_ADMIN;?>jquery-ui.js"></script>-->
	<script src="<?php echo JS_URL;?>general.js" type="text/javascript" ></script>

	<script src="<?php echo JS_URL;?>jquery.countdown.js" type="text/javascript" ></script>
	<script type="text/javascript" src="<?php echo APPLICATION_URL;?>creator/html2canvas.js"></script>

<!--	<script type="text/javascript" src="--><?php //echo APPLICATION_URL;?><!--creator/bootstrap.min.js"></script>-->

    <script type="text/javascript" >
    $("#myInformationDiv").ready(function () {

      $("#myInformationDiv2").show(1000);

    });

	setTimeout(function() {

	$("#myInformationDiv2").hide("fast", function () {
		// use callee so don't have to name the function
		$(this).prev().hide("fast", arguments.callee);
	});

	}, 7000);

	function showhide_commentbox(Stat,Id,Id1)
	{
		if(Stat!="")
		{
			$('#answer'+Id+Id1).slideToggle("slow");
		}
	}

	$(document).ready(function() {
		if(document.getElementById('frontDataValK').value=='front')
		{
			$('#onlyFrontDataK').css("display","block");
		}
		else
		{
			$('#bothdatakmanika').css("display","block");
		}
	});

	function showtee()
	{
		$('#Tees1').css("display","none");
		$('#Tees0').css("display","block");
	}

	function showtee1()
	{
		$('#Tees0').css("display","none");
		$('#Tees1').css("display","block");
	}
	</script>

	<link href='<?php echo IMAGES_URL;?>favicon.ico' rel='icon' type='image/x-icon'/>
	<style>


	#Tees0
	{
		display:block;
	}

	#Tees1
	{
		display:none;
	}

	#onlyFrontDataK ,#bothdatakmanika
	{
		display:none;
	}

    .fpd-recreation div {
        position: relative;
        height: 570px;
        /*margin-left: -42px;*/
    }

    .fpd-recreation img,
    .fpd-recreation canvas,
    .fpd-recreation span {
        position: absolute;
    }
	</style>

</head>
<body id="page1">

	<input type="hidden" id="frontDataValK" value="" />
	<?php if( $mySession->errorMsg!=""){ ?>

	<div id="myInformationDiv" style="position:absolute; width:100%; top:133px; ">

		<div id="myInformationDiv2" align="center" style="position:absolute; width:100%; display:block; color:#000;background-color:#319ebc; height:36px; font-family:Verdana, Geneva, sans-serif;">
		<?=$mySession->errorMsg?>
		</div>
	</div>
	<?php unset($mySession->errorMsg); } ?>

	<?php include ("header_1.phtml"); ?>

	<?php if($myControllerName!="launchcampaign") { ?>
	<!--------------header end--------------->
	<div class="banner">
	  <div class="zerogrid">
		<div class="row block" style="margin-bottom:0px;">
		  <div id="align_both">
			<div class="top_info">
			  <div class="info_left" id="how_in_right">
				<?php if($myControllerName=='myaccount') {
					if($myActionName=='activecampaign') {
						echo 'Active Campaigns';
					} elseif($myActionName=='endedcampaign') {
						echo 'Ended Campaigns';
					} elseif($myActionName=='drafts') {
						echo 'Saved Drafts';
					} elseif($myActionName=='profile') {
						echo 'Profile';
					} elseif($myActionName=='changepassword') {
						echo 'Change Password';
					} elseif($myActionName=='referfriends') {
						echo 'Refer Friends';
					}
				} elseif($myControllerName=='login') {
					if($myActionName=='index') {
//						echo 'Login';
					} elseif($myActionName=='forgotpassword') {
						echo 'Recover your Password';
					} elseif($myActionName=='reset') {
						echo 'Reset your Password';

					}
				} elseif($myControllerName=="payment" && $myActionName=='index') {
					echo 'Enter yout card details';

				} else {
					echo $this->sql[0]['page_title'];
				} ?>
			  </div>
			  <div class="info_right" id="how_in_right_2">
			  </div>
			</div>
		  </div>
		</div>
	  </div>
	</div>

	<!--------------top info end--------------->

					 <?php echo $this->layout()->content;?>


	<?php } elseif($myControllerName=="launchcampaign") { ?>


		<!--------------header end--------------->
		<div class="banner">
		  <div class="zerogrid">
			<div class="row block" style="margin-bottom:0px;">
			  <div id="align_both">
				<div class="top_info">
				  <div class="info_left" id="launch_campaign">
					<?php if($myActionName=='trackorder') {
//					echo 'Track an Order';
					} else {
//					echo 'Launch your Campaign';
					}
					?>
				</div>
				  <div class="info_right" id="launch_campaign_rgt">
				  </div>
				</div>
			  </div>
			</div>
		  </div>
		</div>

        <?php echo $this->layout()->content; ?>


	<?php } else {
		echo $this->layout()->content;
	}
	?>


	<?php include ("footer_1.phtml"); ?>

</body>
</html>