<?php
global $mySession;
$myControllerName=Zend_Controller_Front::getInstance()->getRequest()->getControllerName();		
$myActionName=Zend_Controller_Front::getInstance()->getRequest()->getActionName();	
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=SITE_NAME?> <?php if($this->pageTitle!="" ) { echo " - ".$this->pageTitle; } ?></title>
<!--<link type="text/css" rel="stylesheet" href="<?=CSS_URL?>css/style.css" />-->


<script type="text/javascript" src="<?=JS_URL?>jquery-1.5.js"></script>

<!--<script type="text/javascript" src="<?=JS_URL?>corner.js"></script>-->


<script src="<?=JS_URL?>general.js" type="text/javascript"></script>


<!--<script src="<?=JS_URL?>smooth.js" type="text/javascript"></script>-->

<link rel="stylesheet" href="<?=CSS_URL?>mycss.css" type="text/css">

<script language="javascript">
var ImagesPathforJs='<?=IMAGES_URL?>';
</script>
<!--<link type="text/css" rel="stylesheet" href="<?=CSS_URL?>dhtmlgoodies_calendar.css?random=20051112" media="screen"></LINK>
<SCRIPT type="text/javascript" src="<?=JS_URL?>dhtmlgoodies_calendar.js?random=20060118"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>-->
</head>
<style type="text/css">
html 
{
overflow:auto;
}
body
{
font-family:Verdana, Geneva, sans-serif;
font-size:12px;
color:#626464;	
margin:0px;
padding:0px;
background:#ffffff;
}
</style>
<body id="myBody">
<table width="100%" cellpadding="0" cellspacing="0" align="center">
<tr>
<td align="center" valign="top" style="padding:15px;"><?php //echo $this->layout()->content; ?> </td>
</tr>
</table>
</body>
</html>