 <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td align="left" valign="top"><p><?php echo $this->message; ?></p></td>
    </tr>
    <tr>
        <td align="center" valign="top"><img src="<?=IMAGES_URL?>page_not_found.jpg" border="0" /></td>
    </tr>
    <tr>
        <td align="center" valign="top"><pre><?php echo print_r($this->errorHandlerObject, true); ?></pre></td>
    </tr>
</table>

 <?php /*?> <h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php 
  //die;
  endif ?>

<?php */?>