<?php
global $mySession;
$db=new Db();
?>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo JS_URL;?>jquery.bxslider.js"></script>
<link href="<?php echo CSS_URL;?>jquery.bxslider.css" rel="stylesheet" />

<script>
	$("#myInformationDiv").ready(function () {

		$("#myInformationDiv2").show(1000);

    });

	setTimeout(function() {

    $("#myInformationDiv2").hide("fast", function () {

        // use callee so don't have to name the function

        $(this).prev().hide("fast", arguments.callee);

    });

	}, 7000);

</script>
<script type="text/javascript">
    $(document).ready(function(){
				 $('.bxslider').bxSlider({
  infiniteLoop: false,
 nextSelector: '#next-awf',
  prevSelector: '#prev-awf',
adaptiveHeight: true,
nextText:'<img src="<?php echo APPLICATION_URL;?>images/ar_right.png">',
prevText:'<img src="<?php echo APPLICATION_URL;?>images/ar_left.png">',
pager:false,
slideWidth: 320,
moveSlides: 1,
slideMargin:30,
    minSlides: 3,
    maxSlides: 3
});
				 $('.bxslider1').bxSlider({
  infiniteLoop: false,
 nextSelector: '#next-fund',
  prevSelector: '#prev-fund',
adaptiveHeight: true,
slideMargin:30,
nextText:'<img src="<?php echo APPLICATION_URL;?>images/ar_right.png">',
prevText:'<img src="<?php echo APPLICATION_URL;?>images/ar_left.png">',
pager:false,
slideWidth: 320,
moveSlides: 1,
    minSlides: 3,
    maxSlides: 3

});
				 $('.bxslider2').bxSlider({
  infiniteLoop: false,
slideWidth: 320,
slideMargin:30,
 nextSelector: '#next-unsucess',
  prevSelector: '#prev-unsucess',
adaptiveHeight: true,
nextText:'<img src="<?php echo APPLICATION_URL;?>images/ar_right.png">',
prevText:'<img src="<?php echo APPLICATION_URL;?>images/ar_left.png">',
pager:false,
moveSlides: 1,
    minSlides: 3,
    maxSlides: 3

});
    });
</script>
<style>

.info_textData

{

	width:229px;

	background-color:#000;

	color:#fff;

	font-size:12px;

	font-family:Arial, Helvetica, sans-serif;

	height:30px;

	padding:5px;

	margin-left:117px;

	margin-top:30px;

	border-radius:3px 3px 3px 3px;

	display:none;

	opacity:0.9;



}

</style>
	<div class="user_profile_scr">
          <div class="ar_left"><a href="#" id="prev-awf"></a></div>
          <div class="ar_mid">awaiting funding</div>
          <div class="ar_right"><a href="#"  id="next-awf"></a></div>
        </div>
		<ul class="bxslider">
		<?php
		$slid=$db->runquery("SELECT * , date_add( launch_date, INTERVAL campaign_length DAY ) AS endData FROM ".LAUNCHCAMPAIGN." WHERE date_add( launch_date, INTERVAL campaign_length DAY )>= NOW() and sold<=goal and (campaign_status = '1' and user_id='".$this->id."') ORDER BY endData");
		$counter=0;
		foreach($slid as $key=>$value) {
			$s=$value['sold']; $g=$value['goal']; @$w=($s/$g)*100;
			$urlPath=urlencode($value['url']);

			$k=0; //echo "------------"; die;

			$row1=$db->runQuery("select DATE_ADD('".$value['launch_date']."', INTERVAL '".$value['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$value['launch_date']."', INTERVAL -1 DAY) AS prevDate");
			$counter++;
			$enddate=$row1[0]['nextDate'];
			$startdate=$value['launch_date'];
			$date=date("Y-m-d");
			$newdat2=explode(" ",$enddate);// function breaks string into ARRAY
			$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format
			$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format
			$diff = strtotime($enddate) - strtotime(date('Y-m-d H:i:s'));
			$day_difference = floor($diff / (60*60*24));
			$username=$db->runquery("select * from ".USERS." where user_id='".$value['user_id']."'");

			if($day_difference>0)
			{
		?>

		<li class="col-1-3" >
			<div class="wrap">
			<div class="heading">
				<a href="<?php echo APPLICATION_URL.$urlPath;?>">
				<?php
				//echo SITE_ROOT.'images/usersdesign/'.$value['tee_image'];
				if($value['tee_image']!="" )
				{
					if($value['tee_image']!="" and  file_exists(SITE_ROOT.'images/usersdesign/'.$value['tee_image']))
					{
				?>
				<img data-caman="brightness(10) contrast(30) sepia(60) saturation(-30)"  data-caman-hidpi="<?php echo APPLICATION_URL;?>images/usersdesign/<?php echo $value['tee_image'];?>"  src="<?php echo APPLICATION_URL;?>images/usersdesign/<?php echo $value['tee_image'];?>" width="275" height="275" />
				<?php
					}
					else
					{
				?>
				<img  src="<?php echo IMAGES_URL;?>var.png"width="275" height="275"/>
				<?php
					}
				}
				else
				{
				?>
				<img  src="<?php echo IMAGES_URL;?>var.png"width="275" height="275"/>

				<?php } ?>
				</a>
				<h2><a href="<?php echo APPLICATION_URL.$urlPath;?>"><?php echo $value['title']; ?></a><br><span>by <a href="<?php echo APPLICATION_URL;?>user/view/user_id/<?php echo $username[0]['user_id'];?>"> <?php echo substr($username[0]['public_name'],0,50);?></a></span></h2>
			</div>

			<div class="content">
				 <?php
				$today= date('Y-m-d H:i:s');
				$days=$value['campaign_length'];
				$totaldate= strtotime((date('Y-m-d H:i:s', strtotime($value['launch_date']. ' + '.$days.' day')))) - (strtotime($today));

				 if($w<100)  {  ?>
				<p class="prc_text"><span><?php echo $value['sold'];?></span> shirts were reserved<br>towards a goal of <span><?php echo $value['goal']; ?></span></p>
				<div class="process">
					<div class="pro_image" style="background-image:url(<?php echo IMAGES_URL;?>process.png);height:27px; width:275px;">
						<div class="pro_count" style="background-color:#006853;width:<?=($w*2.75)?>px; height:27px;">&nbsp;</div>
					</div>
					<div class="proc_txt"><span><?=@$w?>%</span> Funded</div>
				<?php } else { ?>
				<div class="process">
					<div class="pro_image" style="background-image:url(<?php echo IMAGES_URL;?>process.png);height:27px; width:275px;">
						<div class="pro_count" style="background-color:#006853;width:275px; height:27px;">&nbsp;</div>
					</div>
					<div class="proc_txt" style="color:#FFFFFF;margin-top:-35px;">100% Funded</div>
					<div class="proc_txt">$<?php echo $value['selling_price'] ?></div>
					<div class="proc_txt" >
					<a href="<?=APPLICATION_URL.$urlPath?>">
					<span >Buy Now &gt;&gt; </span>
					</a>
					</div>

				<?php } ?>
					<script type="text/javascript">

						var start<?=$value['campaign_id']?>=<?=$totaldate?>;

						start<?=$value['campaign_id']?> = parseFloat(start<?=$value['campaign_id']?>);



						var end<?=$value['campaign_id']?> = 0

						var refresh=1000;

						if(start<?=$value['campaign_id']?> >= end<?=$value['campaign_id']?> ){



						mytime<?=$value['campaign_id']?>=setTimeout('display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>)',refresh)

						}

						else { window.location.href="<?=APPLICATION_URL?>product/index";}



						function display_c<?=$value['campaign_id']?>(start1<?=$value['campaign_id']?>){

						start<?=$value['campaign_id']?> = parseFloat(start1<?=$value['campaign_id']?>);

						var end<?=$value['campaign_id']?> = 0

						var refresh=1000;

						if(start<?=$value['campaign_id']?> >= end<?=$value['campaign_id']?> ){

						mytime<?=$value['campaign_id']?>=setTimeout('display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>)',refresh)

						}

						else { window.location.href="<?=APPLICATION_URL?>product/index";}

						}



						function display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>) {



						var days<?=$value['campaign_id']?>=Math.floor(start<?=$value['campaign_id']?> / 86400);

						var hours<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ))/3600)



						var minutes<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ) - (hours<?=$value['campaign_id']?> *3600 ))/60)



						var secs<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ) - (hours<?=$value['campaign_id']?> *3600 ) - (minutes<?=$value['campaign_id']?>*60)))



						 minutes<?=$value['campaign_id']?> = ((minutes<?=$value['campaign_id']?>>0) ? ((minutes<?=$value['campaign_id']?>>9) ? minutes<?=$value['campaign_id']?> : '0'+minutes<?=$value['campaign_id']?>) + "" : "0");



						 secs<?=$value['campaign_id']?> = ((secs<?=$value['campaign_id']?>>0) ? ((secs<?=$value['campaign_id']?>>9) ? secs<?=$value['campaign_id']?> : '0'+secs<?=$value['campaign_id']?>) + "" : "0");

						var x<?=$value['campaign_id']?> =days<?=$value['campaign_id']?> + "D, " + hours<?=$value['campaign_id']?> + "H, " + minutes<?=$value['campaign_id']?> + "M, " +secs<?=$value['campaign_id']?> + "S" ;



						document.getElementById('ct_<?=$value['campaign_id']?>').innerHTML = x<?=$value['campaign_id']?>;

						start<?=$value['campaign_id']?>=start<?=$value['campaign_id']?>- 1;

						tt<?=$value['campaign_id']?>=display_c<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>);

						}

					</script>
                        <div class="proc_time">Time left: <span id="ct_<?=$value['campaign_id']?>">&nbsp;</span></div>
				</div>

			</div>

		</div>
	</li>
    <?php }
		if($counter==3) { $counter=0;}
	} ?>
	</ul>
    <div class="user_profile_scr">
        <div class="ar_left"><a href="#" id="prev-fund"></a></div>
        <div class="ar_mid">funded tees</div>
        <div class="ar_right"><a href="#" id="next-fund"></a></div>
    </div>
	<ul class="bxslider1">
    <?php
		$slid=$db->runquery("SELECT * FROM ".LAUNCHCAMPAIGN."  WHERE sold>=goal and user_id='".$this->id."'");
		$counter=0;
		foreach($slid as $key=>$value) {
			$s=$value['sold']; $g=$value['goal']; @$w=($s/$g)*100;
			$urlPath=urlencode($value['url']);
			$counter++;
			$k=0; //echo "------------"; die;

			$row1=$db->runQuery("select DATE_ADD('".$value['launch_date']."', INTERVAL '".$value['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$value['launch_date']."', INTERVAL -1 DAY) AS prevDate");

			$enddate=$row1[0]['nextDate'];
			$startdate=$value['launch_date'];
			$date=date("Y-m-d");
			$newdat2=explode(" ",$enddate);// function breaks string into ARRAY
			$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format
			$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format
			$diff = strtotime($enddate) - strtotime(date('Y-m-d H:i:s'));
			$day_difference = floor($diff / (60*60*24));
			$username=$db->runquery("select * from ".USERS." where user_id='".$value['user_id']."'");

			{
		?>
		<li class="col-1-3" >
			<div class="wrap">
			<div class="heading">
				<a href="<?php echo APPLICATION_URL.$urlPath;?>">
				<?php
				//echo SITE_ROOT.'images/usersdesign/'.$value['tee_image'];
				if($value['tee_image']!="" )
				{
					if($value['tee_image']!="" and  file_exists(SITE_ROOT.'images/usersdesign/'.$value['tee_image']))
					{
				?>
				<img data-caman="brightness(10) contrast(30) sepia(60) saturation(-30)"  data-caman-hidpi="<?php echo APPLICATION_URL;?>images/usersdesign/<?php echo $value['tee_image'];?>"  src="<?php echo APPLICATION_URL;?>images/usersdesign/<?php echo $value['tee_image'];?>" width="275" height="275" />
				<?php
					}
					else
					{
				?>
				<img  src="<?php echo IMAGES_URL;?>var.png"width="275" height="275"/>
				<?php
					}
				}
				else
				{
				?>
				<img  src="<?php echo IMAGES_URL;?>var.png"width="275" height="275"/>

				<?php } ?>
				</a>
				<h2><a href="<?php echo APPLICATION_URL.$urlPath;?>"><?php echo $value['title']; ?></a><br><span>by <a href="<?php echo APPLICATION_URL;?>user/view/user_id/<?php echo $username[0]['user_id'];?>"> <?php echo substr($username[0]['public_name'],0,50);?></a></span></h2>
			</div>

			<div class="content">
				 <?php
				$today= date('Y-m-d H:i:s');
				$days=$value['campaign_length'];
				$totaldate= strtotime((date('Y-m-d H:i:s', strtotime($value['launch_date']. ' + '.$days.' day')))) - (strtotime($today));

				 if(($value['campaign_status']==0 || $day_difference<=0))  {  ?>

				<div class="process" style="margin-top: 10px;">
					<div class="pro_image" style="background-image:url(<?php echo IMAGES_URL;?>process.png);height:27px; width:275px;">
						<div class="pro_count" style="background-color:#006853;width:275px; height:27px;">&nbsp;</div>
					</div>
					<div class="proc_txt" style="color:#FFFFFF;margin-top:-35px;">100% Funded</div>
					<div class="proc_txt" >$<?php echo $value['selling_price'] ?></div>


					<div class="proc_txt" >
					<a href="<?=APPLICATION_URL.$urlPath?>" >
					<span id="purchase_error<?=$value['campaign_id']?>">Buy Now &gt;&gt; </span>
					</a>
					</div>


				<?php } else { ?>
				<div class="process" style="margin-top: 10px;">
					<div class="pro_image" style="background-image:url(<?php echo IMAGES_URL;?>process.png);height:27px; width:275px;">
						<div class="pro_count" style="background-color:#006853;width:275px; height:27px;">&nbsp;</div>
					</div>
					<div class="proc_txt" style="color:#FFFFFF;margin-top:-35px;">100% Funded</div>
					<div class="proc_txt" >$<?php echo $value['selling_price'] ?></div>
					<div class="proc_txt" >
					<a href="<?=APPLICATION_URL.$urlPath?>">
					<span >Buy Now &gt;&gt; </span>
					</a>
					</div>
				<?php } ?>
				<?php  if($day_difference>0) { ?>
				<script type="text/javascript">

						var start<?=$value['campaign_id']?>=<?=$totaldate?>;

						start<?=$value['campaign_id']?> = parseFloat(start<?=$value['campaign_id']?>);



						var end<?=$value['campaign_id']?> = 0

						var refresh=1000;

						if(start<?=$value['campaign_id']?> >= end<?=$value['campaign_id']?> ){



						mytime<?=$value['campaign_id']?>=setTimeout('display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>)',refresh)

						}

						else { window.location.href="<?=APPLICATION_URL?>product/index";}



						function display_c<?=$value['campaign_id']?>(start1<?=$value['campaign_id']?>){

						start<?=$value['campaign_id']?> = parseFloat(start1<?=$value['campaign_id']?>);

						var end<?=$value['campaign_id']?> = 0

						var refresh=1000;

						if(start<?=$value['campaign_id']?> >= end<?=$value['campaign_id']?> ){

						mytime<?=$value['campaign_id']?>=setTimeout('display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>)',refresh)

						}

						else { window.location.href="<?=APPLICATION_URL?>product/index";}

						}



						function display_ct_<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>) {



						var days<?=$value['campaign_id']?>=Math.floor(start<?=$value['campaign_id']?> / 86400);

						var hours<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ))/3600)



						var minutes<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ) - (hours<?=$value['campaign_id']?> *3600 ))/60)



						var secs<?=$value['campaign_id']?> = Math.floor((start<?=$value['campaign_id']?> - (days<?=$value['campaign_id']?> * 86400 ) - (hours<?=$value['campaign_id']?> *3600 ) - (minutes<?=$value['campaign_id']?>*60)))



						 minutes<?=$value['campaign_id']?> = ((minutes<?=$value['campaign_id']?>>0) ? ((minutes<?=$value['campaign_id']?>>9) ? minutes<?=$value['campaign_id']?> : '0'+minutes<?=$value['campaign_id']?>) + "" : "0");



						 secs<?=$value['campaign_id']?> = ((secs<?=$value['campaign_id']?>>0) ? ((secs<?=$value['campaign_id']?>>9) ? secs<?=$value['campaign_id']?> : '0'+secs<?=$value['campaign_id']?>) + "" : "0");

						var x<?=$value['campaign_id']?> =days<?=$value['campaign_id']?> + "D, " + hours<?=$value['campaign_id']?> + "H, " + minutes<?=$value['campaign_id']?> + "M, " +secs<?=$value['campaign_id']?> + "S" ;



						document.getElementById('ct_<?=$value['campaign_id']?>').innerHTML = x<?=$value['campaign_id']?>;

						start<?=$value['campaign_id']?>=start<?=$value['campaign_id']?>- 1;

						tt<?=$value['campaign_id']?>=display_c<?=$value['campaign_id']?>(start<?=$value['campaign_id']?>);

						}

					</script>
					<div class="proc_time">Time left: <span id="ct_<?=$value['campaign_id']?>">&nbsp;</span></div>
				<?php } else { ?>
					<div class="proc_time">This campaign ended on <?=$enddate?></div>
				<?php } ?>
			</div>

		</div>
	</li>
     <?php }
		if($counter==3) { $counter=0;}
	} ?>
	</ul>
    <div class="user_profile_scr">
        <div class="ar_left"><a href="#" id="prev-unsucess"></a></div>
<!--        <div class="ar_mid">unsuccessful tees</div>-->
        <div class="ar_right"><a href="#" id="next-unsucess"></a></div>
    </div>
	<ul class="bxslider2">
    <?php
		$slid=$db->runquery("SELECT * , date_add( launch_date, INTERVAL campaign_length DAY ) AS endData FROM ".LAUNCHCAMPAIGN." WHERE date_add( launch_date, INTERVAL campaign_length DAY )< NOW() and (goal!=sold and sold < goal) and(campaign_status = '1' and user_id='".$this->id."') ORDER BY endData");

		$counter=0;
		foreach($slid as $key=>$value) {
			$s=$value['sold']; $g=$value['goal']; @$w=($s/$g)*100;
			$urlPath=urlencode($value['url']);

			$k=0; //echo "------------"; die;

			$row1=$db->runQuery("select DATE_ADD('".$value['launch_date']."', INTERVAL '".$value['campaign_length']."' DAY) AS nextDate,DATE_ADD('".$value['launch_date']."', INTERVAL -1 DAY) AS prevDate");

			$enddate=$row1[0]['nextDate'];
			$startdate=$value['launch_date'];
			$date=date("Y-m-d");
			$newdat2=explode(" ",$enddate);// function breaks string into ARRAY
			$newdat3=explode("-",$newdat2[0]);                            // comes in Y-M-D format
			$newdat4=$newdat3[2]."/".$newdat3[1]."/".$newdat3[0];                // D/m/Y format
			$diff = strtotime($enddate) - strtotime(date('Y-m-d H:i:s'));
			$day_difference = floor($diff / (60*60*24));
			$username=$db->runquery("select * from ".USERS." where user_id='".$value['user_id']."'");

			$counter++;
		?>

		<li class="col-1-3" >
			<div class="wrap">
			<div class="heading">
				<a href="<?php echo APPLICATION_URL.$urlPath;?>">
				<?php
				//echo SITE_ROOT.'images/usersdesign/'.$value['tee_image'];
				if($value['tee_image']!="" )
				{
					if($value['tee_image']!="" and  file_exists(SITE_ROOT.'images/usersdesign/'.$value['tee_image']))
					{
				?>
				<img data-caman="brightness(10) contrast(30) sepia(60) saturation(-30)"  data-caman-hidpi="<?php echo APPLICATION_URL;?>images/usersdesign/<?php echo $value['tee_image'];?>"  src="<?php echo APPLICATION_URL;?>images/usersdesign/<?php echo $value['tee_image'];?>" width="275" height="275" />
				<?php
					}
					else
					{
				?>
				<img  src="<?php echo IMAGES_URL;?>var.png"width="275" height="275"/>
				<?php
					}
				}
				else
				{
				?>
				<img  src="<?php echo IMAGES_URL;?>var.png"width="275" height="275"/>

				<?php } ?>
				</a>
				<h2><a href="<?php echo APPLICATION_URL.$urlPath;?>"><?php echo $value['title']; ?></a><br><span>by <a href="<?php echo APPLICATION_URL;?>user/view/user_id/<?php echo $username[0]['user_id'];?>"> <?php echo substr($username[0]['public_name'],0,50);?></a></span></h2>
			</div>

			<div class="content">
				 <?php
				$today= date('Y-m-d H:i:s');
				$days=$value['campaign_length'];
				$totaldate= strtotime((date('Y-m-d H:i:s', strtotime($value['launch_date']. ' + '.$days.' day')))) - (strtotime($today));

				 if($w<100)  {  ?>
				<p class="prc_text"><span><?php echo $value['sold'];?></span> shirts were reserved<br>towards a goal of <span><?php echo $value['goal']; ?></span></p>
				<div class="process">
					<div class="pro_image" style="background-image:url(<?php echo IMAGES_URL;?>process.png);height:27px; width:275px;">
						<div class="pro_count" style="background-color:#006853;width:<?=($w*2.75)?>px; height:27px;">&nbsp;</div>
					</div>
					<div class="proc_txt" >UNSUCCESSFUL</div>
				<?php } else { ?>
				<div class="process" style="margin-top: 10px;">
					<div class="pro_image" style="background-image:url(<?php echo IMAGES_URL;?>process.png);height:27px; width:275px;">
						<div class="pro_count" style="background-color:#006853;width:275px; height:27px;">&nbsp;</div>
					</div>
					<div class="proc_txt" style="color:#FFFFFF;margin-top:-35px;">100% Funded</div>
					<div class="proc_txt" >$<?php echo $value['selling_price'] ?></div>
					<div class="proc_txt" >
					<a href="<?=APPLICATION_URL.$urlPath?>">
					<span >Buy Now &gt;&gt; </span>
					</a>
					</div>
				<?php } ?>
					<div class="proc_time">This campaign has ended.</div>
				</div>

			</div>


		</div>
	</li>
	 <?php if($counter==3) { $counter=0;}
	} ?>
	</ul>

			<script>

            $("#purchase_error"+<?=$value['campaign_id']?>).mouseover(function(e) {

            $("#info_div"+<?=$value['campaign_id']?>).slideDown() ;

            });

            $("#purchase_error"+<?=$value['campaign_id']?>).mouseleave(function(e) {

            $("#info_div"+<?=$value['campaign_id']?>).slideUp() ;

            });

            </script>


