<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-table-1"><?=$this->pageTitle?></span>
    </div>

    <div class="mws-panel-body">
        <div class="mws-panel-toolbar top clearfix">
            <ul>

                 <!--<li><a class="mws-ic-16 ic-accept" href="<?php echo $this->url(array('controller'=>'jobpost', 'action'=>'jobregion'), 'default', true)?>" title="Add">Add</a></li>
           			 <li><a class="mws-ic-16 ic-cross" href="javascript:void(0)" title="Delete" onclick="deleteitem()">Delete</a></li>
               -->
            </ul>
        </div>
        <!--<table class="mws-table">-->
         <table class="mws-table">
            <thead>
                <tr>
                    <th width="5%">S.No</th>
                    <!--<th width="5%"><input type="checkbox" name="deletebcchk" id="deletebcchk" onclick="return checkall(this)" /></th>-->
                    <th width="15%">Site Description</th>
                    <th width="15%">Edit</th>
                 </tr>
            </thead>
            <tbody>
             <?php
					for($i=0;$i<count($this->Data);$i++)
					{
					?>
                    
                <?php
               /* $i=0;
                foreach($this->ResData as $row)
                {*/
                    $start++;
                  

                    ?>
                        <tr>
                            <td style="background-color:#f1f1f1;"><?=$i+1;?></td>
                          <!--  <td>
                                <input name='check<?=$i;?>' id='check<?=$i;?>' value='<?=$this->sql[$i]['region_id'];?>' 
                                    onchange='return check_check("bcdel","deletebcchk")' type='checkbox'>
                            </td>-->
                            <td style="background-color:#f1f1f1;"> <?=$this->Data[$i]['site_desc'];?>
                            </td>
                            <td style="background-color:#f1f1f1;">
                            <a href=<?=APPLICATION_URL_ADMIN?>dashboard/editdesc/desc_id/<?=$this->Data[$i]['desc_id']?>>
                               <img src="<?=APPLICATION_URL_ADMIN;?>css/icons/32/application_form_edit.png" height="16" width="16"   border='0' title='Edit' alt='Edit'>
                            </a>
                            </td>
                        </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
            <div class="mws-panel-header"></div>
    </div>    	
</div>
<script>
function deleteitem()
{
	var r= "";
	var s="";
	var selected=false;
	for(var i=1;document.getElementById('check'+i);i++){
		if(document.getElementById('check'+i).checked==true){	
			r += document.getElementById('check'+i).value+"|";
			selected = true;
		}
	}	
	
	r += '0';
	if(selected){
		var confirmation = confirm("Are you sure want to delete ?");
		if(confirmation!=true){
			return false;
		}	
	
		$.ajax({ url: "<?=APPLICATION_URL_ADMIN."jobpost/deletejobregion"?>",
		type: "POST",
		data: ({Id:r}),
		success: function(data){			
			 window.location.href=window.location.href;
		}});
	} else {
		alert('Please choose a record to delete.');
	}
}
function changestatus(Id,Status)
{
    $.ajax({ 
				type: "POST", 
				url: "<?=APPLICATION_URL_ADMIN?>users/changeuserstatus", 
				data: ({Id:Id,Status:Status}),
				cache: false, 
				success: function(data){				 
				  window.location.href=window.location.href;
			    }
		  });
}
 
function checkall(thisid)
{
  for(var i=1;document.getElementById('check'+i);i++)
  	{
  		if(document.getElementById(thisid.id).checked==true){document.getElementById('check'+i).checked = true;}
  		if(document.getElementById(thisid.id).checked==false){document.getElementById('check'+i).checked = false;}
	}	
}
</script>